licenses(["notice"])  # Apache 2

exports_files([
    "0001-Update-googletest-to-v1.14.0.patch",
    "0002-remove-custom-and-apparently-unused-zlib.patch",
    "0003-Update-json-library-to-3.11.3.patch",
    "0004-Use-int-types-from-cstdint-not-aliases-from-protocon.patch",
    "0005-Replace-internal-string_view-with-absl-string_view.patch",
    "0006-C-style-C-header-includes.patch",
    "0007-Add-comments-for-namespace-closing-in-test-message_r.patch",
    "0008-Update-readme-to-reflect-clang-change-in-8b7e71c.patch",
    "0009-Drop-unused-include-of-cassert.patch",
])
