load(
    "@envoy//source/extensions:extensions_build_config.bzl",
    _EXTENSIONS = "EXTENSIONS",
    _CONTRIB_EXTENSION_PACKAGE_VISIBILITY = "CONTRIB_EXTENSION_PACKAGE_VISIBILITY",
    _EXTENSION_CONFIG_VISIBILITY = "EXTENSION_CONFIG_VISIBILITY",
    _EXTENSION_PACKAGE_VISIBILITY = "EXTENSION_PACKAGE_VISIBILITY",
    _LEGACY_ALWAYSLINK = "LEGACY_ALWAYSLINK",
)

# Drop all wasm extensions (filters, runtimes, access logger, stat sink, bootstrap).
EXTENSIONS = {
    name: target
    for name, target in _EXTENSIONS.items()
    if "wasm" not in name
}

CONTRIB_EXTENSION_PACKAGE_VISIBILITY = _CONTRIB_EXTENSION_PACKAGE_VISIBILITY
EXTENSION_CONFIG_VISIBILITY = _EXTENSION_CONFIG_VISIBILITY
EXTENSION_PACKAGE_VISIBILITY = _EXTENSION_PACKAGE_VISIBILITY
LEGACY_ALWAYSLINK = _LEGACY_ALWAYSLINK
