FROM envoyproxy/envoy:v1.22.0

COPY ./envoy.yaml /etc/envoy.yaml
COPY ./configs /var/lib/envoy
RUN chmod go+x /var/lib/envoy \
    && chmod go+r /etc/envoy.yaml /var/lib/envoy/*
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml"]
