#!/usr/bin/env bash
#
# A git commit hook that runs a format checker on all files touched by the
# commit.
#
# To enable this hook, run `bootstrap`, or run the following from the root of
# the repo. (Note that `bootstrap` will correctly install this even if this code
# is located in a submodule, while the following won't.)
#
# $ ln -s ../../support/hooks/pre-commit .git/hooks/pre-commit

# NOTE: The `tools` directory will be the same relative to the support
# directory, independent of whether we're in a submodule, so no need to use our
# `relpath` helper.
SCRIPT_DIR="$(dirname "$(realpath "$0")")/../../tools"

for i in `git diff-index --name-only --diff-filter=ACM HEAD 2>&1`; do
  echo "Checking format for $i"
  "$SCRIPT_DIR"/check_format.py check $i
  if [[ $? -ne 0 ]]; then
    exit 1
  fi
done
