load("@rules_python//python:py_binary.bzl", "py_binary")

licenses(["notice"])  # Apache 2

py_binary(
    name = "validate_structure",
    srcs = ["validate_structure.py"],
    # deps = [":validate"],
)
