FROM envoyproxy/envoy-dev:latest

COPY . /etc/
RUN chmod go+r /etc/envoy.yaml
RUN chmod go+r /etc/lds.yaml
RUN chmod go+r /etc/cds.yaml

CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "-l", "debug", "--service-cluster", "proxy"]
