envoy_cc_library(
    name = "response_evaluator_lib",
    srcs = ["default_evaluator.cc"],
    hdrs = ["response_evaluator.h"],
    deps = [
      "//source/extensions/filters/http/admission_control:admission_control_filter_lib",
    ],
)

