// Code generated by MockGen. DO NOT EDIT.
// Source: listener_base.go
//
// Generated by this command:
//
//	mockgen -source=listener_base.go -destination=mocks/mock_listener_base.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	shared "github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockListenerFilterConfigHandle is a mock of ListenerFilterConfigHandle interface.
type MockListenerFilterConfigHandle struct {
	ctrl     *gomock.Controller
	recorder *MockListenerFilterConfigHandleMockRecorder
	isgomock struct{}
}

// MockListenerFilterConfigHandleMockRecorder is the mock recorder for MockListenerFilterConfigHandle.
type MockListenerFilterConfigHandleMockRecorder struct {
	mock *MockListenerFilterConfigHandle
}

// NewMockListenerFilterConfigHandle creates a new mock instance.
func NewMockListenerFilterConfigHandle(ctrl *gomock.Controller) *MockListenerFilterConfigHandle {
	mock := &MockListenerFilterConfigHandle{ctrl: ctrl}
	mock.recorder = &MockListenerFilterConfigHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenerFilterConfigHandle) EXPECT() *MockListenerFilterConfigHandleMockRecorder {
	return m.recorder
}

// DefineCounter mocks base method.
func (m *MockListenerFilterConfigHandle) DefineCounter(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineCounter", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineCounter indicates an expected call of DefineCounter.
func (mr *MockListenerFilterConfigHandleMockRecorder) DefineCounter(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineCounter", reflect.TypeOf((*MockListenerFilterConfigHandle)(nil).DefineCounter), name)
}

// DefineGauge mocks base method.
func (m *MockListenerFilterConfigHandle) DefineGauge(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineGauge", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineGauge indicates an expected call of DefineGauge.
func (mr *MockListenerFilterConfigHandleMockRecorder) DefineGauge(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineGauge", reflect.TypeOf((*MockListenerFilterConfigHandle)(nil).DefineGauge), name)
}

// DefineHistogram mocks base method.
func (m *MockListenerFilterConfigHandle) DefineHistogram(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineHistogram", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineHistogram indicates an expected call of DefineHistogram.
func (mr *MockListenerFilterConfigHandleMockRecorder) DefineHistogram(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineHistogram", reflect.TypeOf((*MockListenerFilterConfigHandle)(nil).DefineHistogram), name)
}

// GetScheduler mocks base method.
func (m *MockListenerFilterConfigHandle) GetScheduler() shared.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler")
	ret0, _ := ret[0].(shared.Scheduler)
	return ret0
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockListenerFilterConfigHandleMockRecorder) GetScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockListenerFilterConfigHandle)(nil).GetScheduler))
}

// MockListenerFilterHandle is a mock of ListenerFilterHandle interface.
type MockListenerFilterHandle struct {
	ctrl     *gomock.Controller
	recorder *MockListenerFilterHandleMockRecorder
	isgomock struct{}
}

// MockListenerFilterHandleMockRecorder is the mock recorder for MockListenerFilterHandle.
type MockListenerFilterHandleMockRecorder struct {
	mock *MockListenerFilterHandle
}

// NewMockListenerFilterHandle creates a new mock instance.
func NewMockListenerFilterHandle(ctrl *gomock.Controller) *MockListenerFilterHandle {
	mock := &MockListenerFilterHandle{ctrl: ctrl}
	mock.recorder = &MockListenerFilterHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenerFilterHandle) EXPECT() *MockListenerFilterHandleMockRecorder {
	return m.recorder
}

// CloseSocket mocks base method.
func (m *MockListenerFilterHandle) CloseSocket(details string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSocket", details)
}

// CloseSocket indicates an expected call of CloseSocket.
func (mr *MockListenerFilterHandleMockRecorder) CloseSocket(details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSocket", reflect.TypeOf((*MockListenerFilterHandle)(nil).CloseSocket), details)
}

// ContinueFilterChain mocks base method.
func (m *MockListenerFilterHandle) ContinueFilterChain(success bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ContinueFilterChain", success)
}

// ContinueFilterChain indicates an expected call of ContinueFilterChain.
func (mr *MockListenerFilterHandleMockRecorder) ContinueFilterChain(success any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueFilterChain", reflect.TypeOf((*MockListenerFilterHandle)(nil).ContinueFilterChain), success)
}

// DecrementGauge mocks base method.
func (m *MockListenerFilterHandle) DecrementGauge(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementGauge", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// DecrementGauge indicates an expected call of DecrementGauge.
func (mr *MockListenerFilterHandleMockRecorder) DecrementGauge(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementGauge", reflect.TypeOf((*MockListenerFilterHandle)(nil).DecrementGauge), id, value)
}

// DrainBuffer mocks base method.
func (m *MockListenerFilterHandle) DrainBuffer(length uint64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainBuffer", length)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DrainBuffer indicates an expected call of DrainBuffer.
func (mr *MockListenerFilterHandleMockRecorder) DrainBuffer(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainBuffer", reflect.TypeOf((*MockListenerFilterHandle)(nil).DrainBuffer), length)
}

// GetAddressType mocks base method.
func (m *MockListenerFilterHandle) GetAddressType() shared.AddressType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressType")
	ret0, _ := ret[0].(shared.AddressType)
	return ret0
}

// GetAddressType indicates an expected call of GetAddressType.
func (mr *MockListenerFilterHandleMockRecorder) GetAddressType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressType", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetAddressType))
}

// GetBufferChunk mocks base method.
func (m *MockListenerFilterHandle) GetBufferChunk() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBufferChunk")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetBufferChunk indicates an expected call of GetBufferChunk.
func (mr *MockListenerFilterHandleMockRecorder) GetBufferChunk() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBufferChunk", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetBufferChunk))
}

// GetConnectionStartTimeMs mocks base method.
func (m *MockListenerFilterHandle) GetConnectionStartTimeMs() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionStartTimeMs")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetConnectionStartTimeMs indicates an expected call of GetConnectionStartTimeMs.
func (mr *MockListenerFilterHandleMockRecorder) GetConnectionStartTimeMs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionStartTimeMs", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetConnectionStartTimeMs))
}

// GetDetectedTransportProtocol mocks base method.
func (m *MockListenerFilterHandle) GetDetectedTransportProtocol() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetectedTransportProtocol")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDetectedTransportProtocol indicates an expected call of GetDetectedTransportProtocol.
func (mr *MockListenerFilterHandleMockRecorder) GetDetectedTransportProtocol() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetectedTransportProtocol", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetDetectedTransportProtocol))
}

// GetDirectLocalAddress mocks base method.
func (m *MockListenerFilterHandle) GetDirectLocalAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectLocalAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetDirectLocalAddress indicates an expected call of GetDirectLocalAddress.
func (mr *MockListenerFilterHandleMockRecorder) GetDirectLocalAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectLocalAddress", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetDirectLocalAddress))
}

// GetDirectRemoteAddress mocks base method.
func (m *MockListenerFilterHandle) GetDirectRemoteAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectRemoteAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetDirectRemoteAddress indicates an expected call of GetDirectRemoteAddress.
func (mr *MockListenerFilterHandleMockRecorder) GetDirectRemoteAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectRemoteAddress", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetDirectRemoteAddress))
}

// GetDynamicMetadataNumber mocks base method.
func (m *MockListenerFilterHandle) GetDynamicMetadataNumber(metadataNamespace, key string) (float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDynamicMetadataNumber", metadataNamespace, key)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDynamicMetadataNumber indicates an expected call of GetDynamicMetadataNumber.
func (mr *MockListenerFilterHandleMockRecorder) GetDynamicMetadataNumber(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDynamicMetadataNumber", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetDynamicMetadataNumber), metadataNamespace, key)
}

// GetDynamicMetadataString mocks base method.
func (m *MockListenerFilterHandle) GetDynamicMetadataString(metadataNamespace, key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDynamicMetadataString", metadataNamespace, key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDynamicMetadataString indicates an expected call of GetDynamicMetadataString.
func (mr *MockListenerFilterHandleMockRecorder) GetDynamicMetadataString(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDynamicMetadataString", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetDynamicMetadataString), metadataNamespace, key)
}

// GetFilterState mocks base method.
func (m *MockListenerFilterHandle) GetFilterState(key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterState", key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilterState indicates an expected call of GetFilterState.
func (mr *MockListenerFilterHandleMockRecorder) GetFilterState(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterState", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetFilterState), key)
}

// GetJA3Hash mocks base method.
func (m *MockListenerFilterHandle) GetJA3Hash() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJA3Hash")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetJA3Hash indicates an expected call of GetJA3Hash.
func (mr *MockListenerFilterHandleMockRecorder) GetJA3Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJA3Hash", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetJA3Hash))
}

// GetJA4Hash mocks base method.
func (m *MockListenerFilterHandle) GetJA4Hash() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJA4Hash")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetJA4Hash indicates an expected call of GetJA4Hash.
func (mr *MockListenerFilterHandleMockRecorder) GetJA4Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJA4Hash", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetJA4Hash))
}

// GetLocalAddress mocks base method.
func (m *MockListenerFilterHandle) GetLocalAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetLocalAddress indicates an expected call of GetLocalAddress.
func (mr *MockListenerFilterHandleMockRecorder) GetLocalAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAddress", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetLocalAddress))
}

// GetOriginalDst mocks base method.
func (m *MockListenerFilterHandle) GetOriginalDst() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalDst")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetOriginalDst indicates an expected call of GetOriginalDst.
func (mr *MockListenerFilterHandleMockRecorder) GetOriginalDst() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalDst", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetOriginalDst))
}

// GetRemoteAddress mocks base method.
func (m *MockListenerFilterHandle) GetRemoteAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetRemoteAddress indicates an expected call of GetRemoteAddress.
func (mr *MockListenerFilterHandleMockRecorder) GetRemoteAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteAddress", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetRemoteAddress))
}

// GetRequestedApplicationProtocols mocks base method.
func (m *MockListenerFilterHandle) GetRequestedApplicationProtocols() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedApplicationProtocols")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetRequestedApplicationProtocols indicates an expected call of GetRequestedApplicationProtocols.
func (mr *MockListenerFilterHandleMockRecorder) GetRequestedApplicationProtocols() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedApplicationProtocols", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetRequestedApplicationProtocols))
}

// GetRequestedServerName mocks base method.
func (m *MockListenerFilterHandle) GetRequestedServerName() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedServerName")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRequestedServerName indicates an expected call of GetRequestedServerName.
func (mr *MockListenerFilterHandleMockRecorder) GetRequestedServerName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedServerName", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetRequestedServerName))
}

// GetSSLDNSSans mocks base method.
func (m *MockListenerFilterHandle) GetSSLDNSSans() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLDNSSans")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetSSLDNSSans indicates an expected call of GetSSLDNSSans.
func (mr *MockListenerFilterHandleMockRecorder) GetSSLDNSSans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLDNSSans", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetSSLDNSSans))
}

// GetSSLSubject mocks base method.
func (m *MockListenerFilterHandle) GetSSLSubject() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLSubject")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSSLSubject indicates an expected call of GetSSLSubject.
func (mr *MockListenerFilterHandleMockRecorder) GetSSLSubject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLSubject", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetSSLSubject))
}

// GetSSLURISans mocks base method.
func (m *MockListenerFilterHandle) GetSSLURISans() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLURISans")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetSSLURISans indicates an expected call of GetSSLURISans.
func (mr *MockListenerFilterHandleMockRecorder) GetSSLURISans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLURISans", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetSSLURISans))
}

// GetScheduler mocks base method.
func (m *MockListenerFilterHandle) GetScheduler() shared.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler")
	ret0, _ := ret[0].(shared.Scheduler)
	return ret0
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockListenerFilterHandleMockRecorder) GetScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetScheduler))
}

// GetSocketFD mocks base method.
func (m *MockListenerFilterHandle) GetSocketFD() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketFD")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetSocketFD indicates an expected call of GetSocketFD.
func (mr *MockListenerFilterHandleMockRecorder) GetSocketFD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketFD", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetSocketFD))
}

// GetSocketOptionBytes mocks base method.
func (m *MockListenerFilterHandle) GetSocketOptionBytes(level, name int64, maxSize uint64) ([]byte, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptionBytes", level, name, maxSize)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSocketOptionBytes indicates an expected call of GetSocketOptionBytes.
func (mr *MockListenerFilterHandleMockRecorder) GetSocketOptionBytes(level, name, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptionBytes", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetSocketOptionBytes), level, name, maxSize)
}

// GetSocketOptionInt mocks base method.
func (m *MockListenerFilterHandle) GetSocketOptionInt(level, name int64) (int64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptionInt", level, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSocketOptionInt indicates an expected call of GetSocketOptionInt.
func (mr *MockListenerFilterHandleMockRecorder) GetSocketOptionInt(level, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptionInt", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetSocketOptionInt), level, name)
}

// GetWorkerIndex mocks base method.
func (m *MockListenerFilterHandle) GetWorkerIndex() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerIndex")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetWorkerIndex indicates an expected call of GetWorkerIndex.
func (mr *MockListenerFilterHandleMockRecorder) GetWorkerIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerIndex", reflect.TypeOf((*MockListenerFilterHandle)(nil).GetWorkerIndex))
}

// HttpCallout mocks base method.
func (m *MockListenerFilterHandle) HttpCallout(clusterName string, headers [][2]string, body []byte, timeoutMs uint64, cb shared.HttpCalloutCallback) (shared.HttpCalloutInitResult, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HttpCallout", clusterName, headers, body, timeoutMs, cb)
	ret0, _ := ret[0].(shared.HttpCalloutInitResult)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// HttpCallout indicates an expected call of HttpCallout.
func (mr *MockListenerFilterHandleMockRecorder) HttpCallout(clusterName, headers, body, timeoutMs, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HttpCallout", reflect.TypeOf((*MockListenerFilterHandle)(nil).HttpCallout), clusterName, headers, body, timeoutMs, cb)
}

// IncrementCounter mocks base method.
func (m *MockListenerFilterHandle) IncrementCounter(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockListenerFilterHandleMockRecorder) IncrementCounter(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockListenerFilterHandle)(nil).IncrementCounter), id, value)
}

// IncrementGauge mocks base method.
func (m *MockListenerFilterHandle) IncrementGauge(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementGauge", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementGauge indicates an expected call of IncrementGauge.
func (mr *MockListenerFilterHandleMockRecorder) IncrementGauge(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementGauge", reflect.TypeOf((*MockListenerFilterHandle)(nil).IncrementGauge), id, value)
}

// IsLocalAddressRestored mocks base method.
func (m *MockListenerFilterHandle) IsLocalAddressRestored() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocalAddressRestored")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLocalAddressRestored indicates an expected call of IsLocalAddressRestored.
func (mr *MockListenerFilterHandleMockRecorder) IsLocalAddressRestored() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocalAddressRestored", reflect.TypeOf((*MockListenerFilterHandle)(nil).IsLocalAddressRestored))
}

// IsSSL mocks base method.
func (m *MockListenerFilterHandle) IsSSL() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSSL")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSSL indicates an expected call of IsSSL.
func (mr *MockListenerFilterHandleMockRecorder) IsSSL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSSL", reflect.TypeOf((*MockListenerFilterHandle)(nil).IsSSL))
}

// MaxReadBytes mocks base method.
func (m *MockListenerFilterHandle) MaxReadBytes() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxReadBytes")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// MaxReadBytes indicates an expected call of MaxReadBytes.
func (mr *MockListenerFilterHandleMockRecorder) MaxReadBytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxReadBytes", reflect.TypeOf((*MockListenerFilterHandle)(nil).MaxReadBytes))
}

// RecordHistogramValue mocks base method.
func (m *MockListenerFilterHandle) RecordHistogramValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHistogramValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// RecordHistogramValue indicates an expected call of RecordHistogramValue.
func (mr *MockListenerFilterHandleMockRecorder) RecordHistogramValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHistogramValue", reflect.TypeOf((*MockListenerFilterHandle)(nil).RecordHistogramValue), id, value)
}

// RestoreLocalAddress mocks base method.
func (m *MockListenerFilterHandle) RestoreLocalAddress(address string, port uint32, isIPv6 bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreLocalAddress", address, port, isIPv6)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RestoreLocalAddress indicates an expected call of RestoreLocalAddress.
func (mr *MockListenerFilterHandleMockRecorder) RestoreLocalAddress(address, port, isIPv6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreLocalAddress", reflect.TypeOf((*MockListenerFilterHandle)(nil).RestoreLocalAddress), address, port, isIPv6)
}

// SetDetectedTransportProtocol mocks base method.
func (m *MockListenerFilterHandle) SetDetectedTransportProtocol(protocol string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDetectedTransportProtocol", protocol)
}

// SetDetectedTransportProtocol indicates an expected call of SetDetectedTransportProtocol.
func (mr *MockListenerFilterHandleMockRecorder) SetDetectedTransportProtocol(protocol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDetectedTransportProtocol", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetDetectedTransportProtocol), protocol)
}

// SetDownstreamTransportFailureReason mocks base method.
func (m *MockListenerFilterHandle) SetDownstreamTransportFailureReason(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDownstreamTransportFailureReason", reason)
}

// SetDownstreamTransportFailureReason indicates an expected call of SetDownstreamTransportFailureReason.
func (mr *MockListenerFilterHandleMockRecorder) SetDownstreamTransportFailureReason(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDownstreamTransportFailureReason", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetDownstreamTransportFailureReason), reason)
}

// SetDynamicMetadataNumber mocks base method.
func (m *MockListenerFilterHandle) SetDynamicMetadataNumber(metadataNamespace, key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDynamicMetadataNumber", metadataNamespace, key, value)
}

// SetDynamicMetadataNumber indicates an expected call of SetDynamicMetadataNumber.
func (mr *MockListenerFilterHandleMockRecorder) SetDynamicMetadataNumber(metadataNamespace, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDynamicMetadataNumber", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetDynamicMetadataNumber), metadataNamespace, key, value)
}

// SetDynamicMetadataString mocks base method.
func (m *MockListenerFilterHandle) SetDynamicMetadataString(metadataNamespace, key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDynamicMetadataString", metadataNamespace, key, value)
}

// SetDynamicMetadataString indicates an expected call of SetDynamicMetadataString.
func (mr *MockListenerFilterHandleMockRecorder) SetDynamicMetadataString(metadataNamespace, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDynamicMetadataString", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetDynamicMetadataString), metadataNamespace, key, value)
}

// SetFilterState mocks base method.
func (m *MockListenerFilterHandle) SetFilterState(key, value string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFilterState", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetFilterState indicates an expected call of SetFilterState.
func (mr *MockListenerFilterHandleMockRecorder) SetFilterState(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFilterState", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetFilterState), key, value)
}

// SetGauge mocks base method.
func (m *MockListenerFilterHandle) SetGauge(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockListenerFilterHandleMockRecorder) SetGauge(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetGauge), id, value)
}

// SetJA3Hash mocks base method.
func (m *MockListenerFilterHandle) SetJA3Hash(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetJA3Hash", hash)
}

// SetJA3Hash indicates an expected call of SetJA3Hash.
func (mr *MockListenerFilterHandleMockRecorder) SetJA3Hash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJA3Hash", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetJA3Hash), hash)
}

// SetJA4Hash mocks base method.
func (m *MockListenerFilterHandle) SetJA4Hash(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetJA4Hash", hash)
}

// SetJA4Hash indicates an expected call of SetJA4Hash.
func (mr *MockListenerFilterHandleMockRecorder) SetJA4Hash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJA4Hash", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetJA4Hash), hash)
}

// SetRemoteAddress mocks base method.
func (m *MockListenerFilterHandle) SetRemoteAddress(address string, port uint32, isIPv6 bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteAddress", address, port, isIPv6)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetRemoteAddress indicates an expected call of SetRemoteAddress.
func (mr *MockListenerFilterHandleMockRecorder) SetRemoteAddress(address, port, isIPv6 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteAddress", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetRemoteAddress), address, port, isIPv6)
}

// SetRequestedApplicationProtocols mocks base method.
func (m *MockListenerFilterHandle) SetRequestedApplicationProtocols(protocols []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedApplicationProtocols", protocols)
}

// SetRequestedApplicationProtocols indicates an expected call of SetRequestedApplicationProtocols.
func (mr *MockListenerFilterHandleMockRecorder) SetRequestedApplicationProtocols(protocols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedApplicationProtocols", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetRequestedApplicationProtocols), protocols)
}

// SetRequestedServerName mocks base method.
func (m *MockListenerFilterHandle) SetRequestedServerName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedServerName", name)
}

// SetRequestedServerName indicates an expected call of SetRequestedServerName.
func (mr *MockListenerFilterHandleMockRecorder) SetRequestedServerName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedServerName", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetRequestedServerName), name)
}

// SetSocketOptionBytes mocks base method.
func (m *MockListenerFilterHandle) SetSocketOptionBytes(level, name int64, value []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSocketOptionBytes", level, name, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetSocketOptionBytes indicates an expected call of SetSocketOptionBytes.
func (mr *MockListenerFilterHandleMockRecorder) SetSocketOptionBytes(level, name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSocketOptionBytes", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetSocketOptionBytes), level, name, value)
}

// SetSocketOptionInt mocks base method.
func (m *MockListenerFilterHandle) SetSocketOptionInt(level, name, value int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSocketOptionInt", level, name, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetSocketOptionInt indicates an expected call of SetSocketOptionInt.
func (mr *MockListenerFilterHandleMockRecorder) SetSocketOptionInt(level, name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSocketOptionInt", reflect.TypeOf((*MockListenerFilterHandle)(nil).SetSocketOptionInt), level, name, value)
}

// UseOriginalDst mocks base method.
func (m *MockListenerFilterHandle) UseOriginalDst(useOriginalDst bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseOriginalDst", useOriginalDst)
}

// UseOriginalDst indicates an expected call of UseOriginalDst.
func (mr *MockListenerFilterHandleMockRecorder) UseOriginalDst(useOriginalDst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseOriginalDst", reflect.TypeOf((*MockListenerFilterHandle)(nil).UseOriginalDst), useOriginalDst)
}

// WriteToSocket mocks base method.
func (m *MockListenerFilterHandle) WriteToSocket(data []byte) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteToSocket", data)
	ret0, _ := ret[0].(int64)
	return ret0
}

// WriteToSocket indicates an expected call of WriteToSocket.
func (mr *MockListenerFilterHandleMockRecorder) WriteToSocket(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteToSocket", reflect.TypeOf((*MockListenerFilterHandle)(nil).WriteToSocket), data)
}
