// Code generated by MockGen. DO NOT EDIT.
// Source: network.go
//
// Generated by this command:
//
//	mockgen -source=network.go -destination=mocks/mock_network.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	shared "github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkFilter is a mock of NetworkFilter interface.
type MockNetworkFilter struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterMockRecorder
	isgomock struct{}
}

// MockNetworkFilterMockRecorder is the mock recorder for MockNetworkFilter.
type MockNetworkFilterMockRecorder struct {
	mock *MockNetworkFilter
}

// NewMockNetworkFilter creates a new mock instance.
func NewMockNetworkFilter(ctrl *gomock.Controller) *MockNetworkFilter {
	mock := &MockNetworkFilter{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilter) EXPECT() *MockNetworkFilterMockRecorder {
	return m.recorder
}

// OnAboveWriteBufferHighWatermark mocks base method.
func (m *MockNetworkFilter) OnAboveWriteBufferHighWatermark(handle shared.NetworkFilterHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAboveWriteBufferHighWatermark", handle)
}

// OnAboveWriteBufferHighWatermark indicates an expected call of OnAboveWriteBufferHighWatermark.
func (mr *MockNetworkFilterMockRecorder) OnAboveWriteBufferHighWatermark(handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAboveWriteBufferHighWatermark", reflect.TypeOf((*MockNetworkFilter)(nil).OnAboveWriteBufferHighWatermark), handle)
}

// OnBelowWriteBufferLowWatermark mocks base method.
func (m *MockNetworkFilter) OnBelowWriteBufferLowWatermark(handle shared.NetworkFilterHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBelowWriteBufferLowWatermark", handle)
}

// OnBelowWriteBufferLowWatermark indicates an expected call of OnBelowWriteBufferLowWatermark.
func (mr *MockNetworkFilterMockRecorder) OnBelowWriteBufferLowWatermark(handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBelowWriteBufferLowWatermark", reflect.TypeOf((*MockNetworkFilter)(nil).OnBelowWriteBufferLowWatermark), handle)
}

// OnDestroy mocks base method.
func (m *MockNetworkFilter) OnDestroy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDestroy")
}

// OnDestroy indicates an expected call of OnDestroy.
func (mr *MockNetworkFilterMockRecorder) OnDestroy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDestroy", reflect.TypeOf((*MockNetworkFilter)(nil).OnDestroy))
}

// OnEvent mocks base method.
func (m *MockNetworkFilter) OnEvent(handle shared.NetworkFilterHandle, event shared.NetworkConnectionEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent", handle, event)
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockNetworkFilterMockRecorder) OnEvent(handle, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockNetworkFilter)(nil).OnEvent), handle, event)
}

// OnNewConnection mocks base method.
func (m *MockNetworkFilter) OnNewConnection(handle shared.NetworkFilterHandle) shared.NetworkFilterDataStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnNewConnection", handle)
	ret0, _ := ret[0].(shared.NetworkFilterDataStatus)
	return ret0
}

// OnNewConnection indicates an expected call of OnNewConnection.
func (mr *MockNetworkFilterMockRecorder) OnNewConnection(handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNewConnection", reflect.TypeOf((*MockNetworkFilter)(nil).OnNewConnection), handle)
}

// OnRead mocks base method.
func (m *MockNetworkFilter) OnRead(handle shared.NetworkFilterHandle, dataLength uint64, endOfStream bool) shared.NetworkFilterDataStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnRead", handle, dataLength, endOfStream)
	ret0, _ := ret[0].(shared.NetworkFilterDataStatus)
	return ret0
}

// OnRead indicates an expected call of OnRead.
func (mr *MockNetworkFilterMockRecorder) OnRead(handle, dataLength, endOfStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRead", reflect.TypeOf((*MockNetworkFilter)(nil).OnRead), handle, dataLength, endOfStream)
}

// OnWrite mocks base method.
func (m *MockNetworkFilter) OnWrite(handle shared.NetworkFilterHandle, dataLength uint64, endOfStream bool) shared.NetworkFilterDataStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnWrite", handle, dataLength, endOfStream)
	ret0, _ := ret[0].(shared.NetworkFilterDataStatus)
	return ret0
}

// OnWrite indicates an expected call of OnWrite.
func (mr *MockNetworkFilterMockRecorder) OnWrite(handle, dataLength, endOfStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnWrite", reflect.TypeOf((*MockNetworkFilter)(nil).OnWrite), handle, dataLength, endOfStream)
}

// MockNetworkFilterFactory is a mock of NetworkFilterFactory interface.
type MockNetworkFilterFactory struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterFactoryMockRecorder
	isgomock struct{}
}

// MockNetworkFilterFactoryMockRecorder is the mock recorder for MockNetworkFilterFactory.
type MockNetworkFilterFactoryMockRecorder struct {
	mock *MockNetworkFilterFactory
}

// NewMockNetworkFilterFactory creates a new mock instance.
func NewMockNetworkFilterFactory(ctrl *gomock.Controller) *MockNetworkFilterFactory {
	mock := &MockNetworkFilterFactory{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilterFactory) EXPECT() *MockNetworkFilterFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetworkFilterFactory) Create(handle shared.NetworkFilterHandle) shared.NetworkFilter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", handle)
	ret0, _ := ret[0].(shared.NetworkFilter)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNetworkFilterFactoryMockRecorder) Create(handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetworkFilterFactory)(nil).Create), handle)
}

// OnDestroy mocks base method.
func (m *MockNetworkFilterFactory) OnDestroy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDestroy")
}

// OnDestroy indicates an expected call of OnDestroy.
func (mr *MockNetworkFilterFactoryMockRecorder) OnDestroy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDestroy", reflect.TypeOf((*MockNetworkFilterFactory)(nil).OnDestroy))
}

// MockNetworkFilterConfigFactory is a mock of NetworkFilterConfigFactory interface.
type MockNetworkFilterConfigFactory struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterConfigFactoryMockRecorder
	isgomock struct{}
}

// MockNetworkFilterConfigFactoryMockRecorder is the mock recorder for MockNetworkFilterConfigFactory.
type MockNetworkFilterConfigFactoryMockRecorder struct {
	mock *MockNetworkFilterConfigFactory
}

// NewMockNetworkFilterConfigFactory creates a new mock instance.
func NewMockNetworkFilterConfigFactory(ctrl *gomock.Controller) *MockNetworkFilterConfigFactory {
	mock := &MockNetworkFilterConfigFactory{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterConfigFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilterConfigFactory) EXPECT() *MockNetworkFilterConfigFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetworkFilterConfigFactory) Create(handle shared.NetworkFilterConfigHandle, unparsedConfig []byte) (shared.NetworkFilterFactory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", handle, unparsedConfig)
	ret0, _ := ret[0].(shared.NetworkFilterFactory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNetworkFilterConfigFactoryMockRecorder) Create(handle, unparsedConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetworkFilterConfigFactory)(nil).Create), handle, unparsedConfig)
}

// MockNetworkFilterConfigHandle is a mock of NetworkFilterConfigHandle interface.
type MockNetworkFilterConfigHandle struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterConfigHandleMockRecorder
	isgomock struct{}
}

// MockNetworkFilterConfigHandleMockRecorder is the mock recorder for MockNetworkFilterConfigHandle.
type MockNetworkFilterConfigHandleMockRecorder struct {
	mock *MockNetworkFilterConfigHandle
}

// NewMockNetworkFilterConfigHandle creates a new mock instance.
func NewMockNetworkFilterConfigHandle(ctrl *gomock.Controller) *MockNetworkFilterConfigHandle {
	mock := &MockNetworkFilterConfigHandle{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterConfigHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilterConfigHandle) EXPECT() *MockNetworkFilterConfigHandleMockRecorder {
	return m.recorder
}

// DefineCounter mocks base method.
func (m *MockNetworkFilterConfigHandle) DefineCounter(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineCounter", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineCounter indicates an expected call of DefineCounter.
func (mr *MockNetworkFilterConfigHandleMockRecorder) DefineCounter(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineCounter", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).DefineCounter), name)
}

// DefineGauge mocks base method.
func (m *MockNetworkFilterConfigHandle) DefineGauge(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineGauge", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineGauge indicates an expected call of DefineGauge.
func (mr *MockNetworkFilterConfigHandleMockRecorder) DefineGauge(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineGauge", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).DefineGauge), name)
}

// DefineHistogram mocks base method.
func (m *MockNetworkFilterConfigHandle) DefineHistogram(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineHistogram", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineHistogram indicates an expected call of DefineHistogram.
func (mr *MockNetworkFilterConfigHandleMockRecorder) DefineHistogram(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineHistogram", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).DefineHistogram), name)
}

// GetScheduler mocks base method.
func (m *MockNetworkFilterConfigHandle) GetScheduler() shared.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler")
	ret0, _ := ret[0].(shared.Scheduler)
	return ret0
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockNetworkFilterConfigHandleMockRecorder) GetScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).GetScheduler))
}

// MockNetworkFilterHandle is a mock of NetworkFilterHandle interface.
type MockNetworkFilterHandle struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterHandleMockRecorder
	isgomock struct{}
}

// MockNetworkFilterHandleMockRecorder is the mock recorder for MockNetworkFilterHandle.
type MockNetworkFilterHandleMockRecorder struct {
	mock *MockNetworkFilterHandle
}

// NewMockNetworkFilterHandle creates a new mock instance.
func NewMockNetworkFilterHandle(ctrl *gomock.Controller) *MockNetworkFilterHandle {
	mock := &MockNetworkFilterHandle{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilterHandle) EXPECT() *MockNetworkFilterHandleMockRecorder {
	return m.recorder
}

// AboveHighWatermark mocks base method.
func (m *MockNetworkFilterHandle) AboveHighWatermark() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AboveHighWatermark")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AboveHighWatermark indicates an expected call of AboveHighWatermark.
func (mr *MockNetworkFilterHandleMockRecorder) AboveHighWatermark() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AboveHighWatermark", reflect.TypeOf((*MockNetworkFilterHandle)(nil).AboveHighWatermark))
}

// AppendReadBuffer mocks base method.
func (m *MockNetworkFilterHandle) AppendReadBuffer(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendReadBuffer", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AppendReadBuffer indicates an expected call of AppendReadBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) AppendReadBuffer(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendReadBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).AppendReadBuffer), data)
}

// AppendWriteBuffer mocks base method.
func (m *MockNetworkFilterHandle) AppendWriteBuffer(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendWriteBuffer", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AppendWriteBuffer indicates an expected call of AppendWriteBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) AppendWriteBuffer(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendWriteBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).AppendWriteBuffer), data)
}

// Close mocks base method.
func (m *MockNetworkFilterHandle) Close(closeType shared.NetworkConnectionCloseType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", closeType)
}

// Close indicates an expected call of Close.
func (mr *MockNetworkFilterHandleMockRecorder) Close(closeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNetworkFilterHandle)(nil).Close), closeType)
}

// CloseWithDetails mocks base method.
func (m *MockNetworkFilterHandle) CloseWithDetails(closeType shared.NetworkConnectionCloseType, details string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseWithDetails", closeType, details)
}

// CloseWithDetails indicates an expected call of CloseWithDetails.
func (mr *MockNetworkFilterHandleMockRecorder) CloseWithDetails(closeType, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWithDetails", reflect.TypeOf((*MockNetworkFilterHandle)(nil).CloseWithDetails), closeType, details)
}

// ContinueReading mocks base method.
func (m *MockNetworkFilterHandle) ContinueReading() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ContinueReading")
}

// ContinueReading indicates an expected call of ContinueReading.
func (mr *MockNetworkFilterHandleMockRecorder) ContinueReading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueReading", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ContinueReading))
}

// DecrementGauge mocks base method.
func (m *MockNetworkFilterHandle) DecrementGauge(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementGauge", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// DecrementGauge indicates an expected call of DecrementGauge.
func (mr *MockNetworkFilterHandleMockRecorder) DecrementGauge(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementGauge", reflect.TypeOf((*MockNetworkFilterHandle)(nil).DecrementGauge), id, value)
}

// DisableClose mocks base method.
func (m *MockNetworkFilterHandle) DisableClose(disabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisableClose", disabled)
}

// DisableClose indicates an expected call of DisableClose.
func (mr *MockNetworkFilterHandleMockRecorder) DisableClose(disabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableClose", reflect.TypeOf((*MockNetworkFilterHandle)(nil).DisableClose), disabled)
}

// DrainReadBuffer mocks base method.
func (m *MockNetworkFilterHandle) DrainReadBuffer(length uint64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainReadBuffer", length)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DrainReadBuffer indicates an expected call of DrainReadBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) DrainReadBuffer(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainReadBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).DrainReadBuffer), length)
}

// DrainWriteBuffer mocks base method.
func (m *MockNetworkFilterHandle) DrainWriteBuffer(length uint64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainWriteBuffer", length)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DrainWriteBuffer indicates an expected call of DrainWriteBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) DrainWriteBuffer(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainWriteBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).DrainWriteBuffer), length)
}

// EnableHalfClose mocks base method.
func (m *MockNetworkFilterHandle) EnableHalfClose(enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableHalfClose", enabled)
}

// EnableHalfClose indicates an expected call of EnableHalfClose.
func (mr *MockNetworkFilterHandleMockRecorder) EnableHalfClose(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableHalfClose", reflect.TypeOf((*MockNetworkFilterHandle)(nil).EnableHalfClose), enabled)
}

// GetBufferLimit mocks base method.
func (m *MockNetworkFilterHandle) GetBufferLimit() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBufferLimit")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetBufferLimit indicates an expected call of GetBufferLimit.
func (mr *MockNetworkFilterHandleMockRecorder) GetBufferLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBufferLimit", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetBufferLimit))
}

// GetClusterHostCount mocks base method.
func (m *MockNetworkFilterHandle) GetClusterHostCount(clusterName string, priority uint32) (shared.ClusterHostCount, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterHostCount", clusterName, priority)
	ret0, _ := ret[0].(shared.ClusterHostCount)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClusterHostCount indicates an expected call of GetClusterHostCount.
func (mr *MockNetworkFilterHandleMockRecorder) GetClusterHostCount(clusterName, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterHostCount", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetClusterHostCount), clusterName, priority)
}

// GetConnectionID mocks base method.
func (m *MockNetworkFilterHandle) GetConnectionID() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionID")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetConnectionID indicates an expected call of GetConnectionID.
func (mr *MockNetworkFilterHandleMockRecorder) GetConnectionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionID", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetConnectionID))
}

// GetConnectionState mocks base method.
func (m *MockNetworkFilterHandle) GetConnectionState() shared.NetworkConnectionState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionState")
	ret0, _ := ret[0].(shared.NetworkConnectionState)
	return ret0
}

// GetConnectionState indicates an expected call of GetConnectionState.
func (mr *MockNetworkFilterHandleMockRecorder) GetConnectionState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionState", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetConnectionState))
}

// GetDirectRemoteAddress mocks base method.
func (m *MockNetworkFilterHandle) GetDirectRemoteAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectRemoteAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetDirectRemoteAddress indicates an expected call of GetDirectRemoteAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetDirectRemoteAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectRemoteAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetDirectRemoteAddress))
}

// GetDynamicMetadataBool mocks base method.
func (m *MockNetworkFilterHandle) GetDynamicMetadataBool(metadataNamespace, key string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDynamicMetadataBool", metadataNamespace, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDynamicMetadataBool indicates an expected call of GetDynamicMetadataBool.
func (mr *MockNetworkFilterHandleMockRecorder) GetDynamicMetadataBool(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDynamicMetadataBool", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetDynamicMetadataBool), metadataNamespace, key)
}

// GetDynamicMetadataNumber mocks base method.
func (m *MockNetworkFilterHandle) GetDynamicMetadataNumber(metadataNamespace, key string) (float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDynamicMetadataNumber", metadataNamespace, key)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDynamicMetadataNumber indicates an expected call of GetDynamicMetadataNumber.
func (mr *MockNetworkFilterHandleMockRecorder) GetDynamicMetadataNumber(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDynamicMetadataNumber", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetDynamicMetadataNumber), metadataNamespace, key)
}

// GetDynamicMetadataString mocks base method.
func (m *MockNetworkFilterHandle) GetDynamicMetadataString(metadataNamespace, key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDynamicMetadataString", metadataNamespace, key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetDynamicMetadataString indicates an expected call of GetDynamicMetadataString.
func (mr *MockNetworkFilterHandleMockRecorder) GetDynamicMetadataString(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDynamicMetadataString", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetDynamicMetadataString), metadataNamespace, key)
}

// GetFilterState mocks base method.
func (m *MockNetworkFilterHandle) GetFilterState(key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterState", key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilterState indicates an expected call of GetFilterState.
func (mr *MockNetworkFilterHandleMockRecorder) GetFilterState(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterState", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetFilterState), key)
}

// GetFilterStateTyped mocks base method.
func (m *MockNetworkFilterHandle) GetFilterStateTyped(key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterStateTyped", key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilterStateTyped indicates an expected call of GetFilterStateTyped.
func (mr *MockNetworkFilterHandleMockRecorder) GetFilterStateTyped(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterStateTyped", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetFilterStateTyped), key)
}

// GetLocalAddress mocks base method.
func (m *MockNetworkFilterHandle) GetLocalAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetLocalAddress indicates an expected call of GetLocalAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetLocalAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetLocalAddress))
}

// GetReadBufferChunks mocks base method.
func (m *MockNetworkFilterHandle) GetReadBufferChunks() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReadBufferChunks")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetReadBufferChunks indicates an expected call of GetReadBufferChunks.
func (mr *MockNetworkFilterHandleMockRecorder) GetReadBufferChunks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReadBufferChunks", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetReadBufferChunks))
}

// GetReadBufferSize mocks base method.
func (m *MockNetworkFilterHandle) GetReadBufferSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReadBufferSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetReadBufferSize indicates an expected call of GetReadBufferSize.
func (mr *MockNetworkFilterHandleMockRecorder) GetReadBufferSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReadBufferSize", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetReadBufferSize))
}

// GetRemoteAddress mocks base method.
func (m *MockNetworkFilterHandle) GetRemoteAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetRemoteAddress indicates an expected call of GetRemoteAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetRemoteAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetRemoteAddress))
}

// GetRequestedServerName mocks base method.
func (m *MockNetworkFilterHandle) GetRequestedServerName() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedServerName")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRequestedServerName indicates an expected call of GetRequestedServerName.
func (mr *MockNetworkFilterHandleMockRecorder) GetRequestedServerName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedServerName", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetRequestedServerName))
}

// GetSSLDNSSans mocks base method.
func (m *MockNetworkFilterHandle) GetSSLDNSSans() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLDNSSans")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetSSLDNSSans indicates an expected call of GetSSLDNSSans.
func (mr *MockNetworkFilterHandleMockRecorder) GetSSLDNSSans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLDNSSans", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSSLDNSSans))
}

// GetSSLSubject mocks base method.
func (m *MockNetworkFilterHandle) GetSSLSubject() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLSubject")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSSLSubject indicates an expected call of GetSSLSubject.
func (mr *MockNetworkFilterHandleMockRecorder) GetSSLSubject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLSubject", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSSLSubject))
}

// GetSSLURISans mocks base method.
func (m *MockNetworkFilterHandle) GetSSLURISans() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLURISans")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetSSLURISans indicates an expected call of GetSSLURISans.
func (mr *MockNetworkFilterHandleMockRecorder) GetSSLURISans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLURISans", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSSLURISans))
}

// GetScheduler mocks base method.
func (m *MockNetworkFilterHandle) GetScheduler() shared.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler")
	ret0, _ := ret[0].(shared.Scheduler)
	return ret0
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockNetworkFilterHandleMockRecorder) GetScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetScheduler))
}

// GetSocketOptionBytes mocks base method.
func (m *MockNetworkFilterHandle) GetSocketOptionBytes(level, name int64, state shared.SocketOptionState) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptionBytes", level, name, state)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSocketOptionBytes indicates an expected call of GetSocketOptionBytes.
func (mr *MockNetworkFilterHandleMockRecorder) GetSocketOptionBytes(level, name, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptionBytes", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSocketOptionBytes), level, name, state)
}

// GetSocketOptionInt mocks base method.
func (m *MockNetworkFilterHandle) GetSocketOptionInt(level, name int64, state shared.SocketOptionState) (int64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptionInt", level, name, state)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSocketOptionInt indicates an expected call of GetSocketOptionInt.
func (mr *MockNetworkFilterHandleMockRecorder) GetSocketOptionInt(level, name, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptionInt", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSocketOptionInt), level, name, state)
}

// GetSocketOptions mocks base method.
func (m *MockNetworkFilterHandle) GetSocketOptions() []shared.SocketOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptions")
	ret0, _ := ret[0].([]shared.SocketOption)
	return ret0
}

// GetSocketOptions indicates an expected call of GetSocketOptions.
func (mr *MockNetworkFilterHandleMockRecorder) GetSocketOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptions", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSocketOptions))
}

// GetUpstreamHostAddress mocks base method.
func (m *MockNetworkFilterHandle) GetUpstreamHostAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpstreamHostAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetUpstreamHostAddress indicates an expected call of GetUpstreamHostAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetUpstreamHostAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpstreamHostAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetUpstreamHostAddress))
}

// GetUpstreamHostCluster mocks base method.
func (m *MockNetworkFilterHandle) GetUpstreamHostCluster() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpstreamHostCluster")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUpstreamHostCluster indicates an expected call of GetUpstreamHostCluster.
func (mr *MockNetworkFilterHandleMockRecorder) GetUpstreamHostCluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpstreamHostCluster", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetUpstreamHostCluster))
}

// GetUpstreamHostHostname mocks base method.
func (m *MockNetworkFilterHandle) GetUpstreamHostHostname() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpstreamHostHostname")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUpstreamHostHostname indicates an expected call of GetUpstreamHostHostname.
func (mr *MockNetworkFilterHandleMockRecorder) GetUpstreamHostHostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpstreamHostHostname", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetUpstreamHostHostname))
}

// GetWorkerIndex mocks base method.
func (m *MockNetworkFilterHandle) GetWorkerIndex() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerIndex")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetWorkerIndex indicates an expected call of GetWorkerIndex.
func (mr *MockNetworkFilterHandleMockRecorder) GetWorkerIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerIndex", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetWorkerIndex))
}

// GetWriteBufferChunks mocks base method.
func (m *MockNetworkFilterHandle) GetWriteBufferChunks() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWriteBufferChunks")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetWriteBufferChunks indicates an expected call of GetWriteBufferChunks.
func (mr *MockNetworkFilterHandleMockRecorder) GetWriteBufferChunks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWriteBufferChunks", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetWriteBufferChunks))
}

// GetWriteBufferSize mocks base method.
func (m *MockNetworkFilterHandle) GetWriteBufferSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWriteBufferSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetWriteBufferSize indicates an expected call of GetWriteBufferSize.
func (mr *MockNetworkFilterHandleMockRecorder) GetWriteBufferSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWriteBufferSize", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetWriteBufferSize))
}

// HasUpstreamHost mocks base method.
func (m *MockNetworkFilterHandle) HasUpstreamHost() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUpstreamHost")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasUpstreamHost indicates an expected call of HasUpstreamHost.
func (mr *MockNetworkFilterHandleMockRecorder) HasUpstreamHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUpstreamHost", reflect.TypeOf((*MockNetworkFilterHandle)(nil).HasUpstreamHost))
}

// HttpCallout mocks base method.
func (m *MockNetworkFilterHandle) HttpCallout(clusterName string, headers [][2]string, body []byte, timeoutMs uint64, cb shared.HttpCalloutCallback) (shared.HttpCalloutInitResult, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HttpCallout", clusterName, headers, body, timeoutMs, cb)
	ret0, _ := ret[0].(shared.HttpCalloutInitResult)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// HttpCallout indicates an expected call of HttpCallout.
func (mr *MockNetworkFilterHandleMockRecorder) HttpCallout(clusterName, headers, body, timeoutMs, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HttpCallout", reflect.TypeOf((*MockNetworkFilterHandle)(nil).HttpCallout), clusterName, headers, body, timeoutMs, cb)
}

// IncrementCounter mocks base method.
func (m *MockNetworkFilterHandle) IncrementCounter(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockNetworkFilterHandleMockRecorder) IncrementCounter(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IncrementCounter), id, value)
}

// IncrementGauge mocks base method.
func (m *MockNetworkFilterHandle) IncrementGauge(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementGauge", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementGauge indicates an expected call of IncrementGauge.
func (mr *MockNetworkFilterHandleMockRecorder) IncrementGauge(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementGauge", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IncrementGauge), id, value)
}

// InjectReadData mocks base method.
func (m *MockNetworkFilterHandle) InjectReadData(data []byte, endOfStream bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectReadData", data, endOfStream)
}

// InjectReadData indicates an expected call of InjectReadData.
func (mr *MockNetworkFilterHandleMockRecorder) InjectReadData(data, endOfStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectReadData", reflect.TypeOf((*MockNetworkFilterHandle)(nil).InjectReadData), data, endOfStream)
}

// InjectWriteData mocks base method.
func (m *MockNetworkFilterHandle) InjectWriteData(data []byte, endOfStream bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectWriteData", data, endOfStream)
}

// InjectWriteData indicates an expected call of InjectWriteData.
func (mr *MockNetworkFilterHandleMockRecorder) InjectWriteData(data, endOfStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectWriteData", reflect.TypeOf((*MockNetworkFilterHandle)(nil).InjectWriteData), data, endOfStream)
}

// IsHalfCloseEnabled mocks base method.
func (m *MockNetworkFilterHandle) IsHalfCloseEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHalfCloseEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHalfCloseEnabled indicates an expected call of IsHalfCloseEnabled.
func (mr *MockNetworkFilterHandleMockRecorder) IsHalfCloseEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHalfCloseEnabled", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IsHalfCloseEnabled))
}

// IsSSL mocks base method.
func (m *MockNetworkFilterHandle) IsSSL() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSSL")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSSL indicates an expected call of IsSSL.
func (mr *MockNetworkFilterHandleMockRecorder) IsSSL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSSL", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IsSSL))
}

// PrependReadBuffer mocks base method.
func (m *MockNetworkFilterHandle) PrependReadBuffer(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrependReadBuffer", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PrependReadBuffer indicates an expected call of PrependReadBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) PrependReadBuffer(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrependReadBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).PrependReadBuffer), data)
}

// PrependWriteBuffer mocks base method.
func (m *MockNetworkFilterHandle) PrependWriteBuffer(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrependWriteBuffer", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PrependWriteBuffer indicates an expected call of PrependWriteBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) PrependWriteBuffer(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrependWriteBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).PrependWriteBuffer), data)
}

// ReadDisable mocks base method.
func (m *MockNetworkFilterHandle) ReadDisable(disable bool) shared.NetworkReadDisableStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDisable", disable)
	ret0, _ := ret[0].(shared.NetworkReadDisableStatus)
	return ret0
}

// ReadDisable indicates an expected call of ReadDisable.
func (mr *MockNetworkFilterHandleMockRecorder) ReadDisable(disable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDisable", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ReadDisable), disable)
}

// ReadEnabled mocks base method.
func (m *MockNetworkFilterHandle) ReadEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReadEnabled indicates an expected call of ReadEnabled.
func (mr *MockNetworkFilterHandleMockRecorder) ReadEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEnabled", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ReadEnabled))
}

// RecordHistogramValue mocks base method.
func (m *MockNetworkFilterHandle) RecordHistogramValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHistogramValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// RecordHistogramValue indicates an expected call of RecordHistogramValue.
func (mr *MockNetworkFilterHandleMockRecorder) RecordHistogramValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHistogramValue", reflect.TypeOf((*MockNetworkFilterHandle)(nil).RecordHistogramValue), id, value)
}

// SetBufferLimits mocks base method.
func (m *MockNetworkFilterHandle) SetBufferLimits(limit uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBufferLimits", limit)
}

// SetBufferLimits indicates an expected call of SetBufferLimits.
func (mr *MockNetworkFilterHandleMockRecorder) SetBufferLimits(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBufferLimits", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetBufferLimits), limit)
}

// SetDynamicMetadataBool mocks base method.
func (m *MockNetworkFilterHandle) SetDynamicMetadataBool(metadataNamespace, key string, value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDynamicMetadataBool", metadataNamespace, key, value)
}

// SetDynamicMetadataBool indicates an expected call of SetDynamicMetadataBool.
func (mr *MockNetworkFilterHandleMockRecorder) SetDynamicMetadataBool(metadataNamespace, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDynamicMetadataBool", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetDynamicMetadataBool), metadataNamespace, key, value)
}

// SetDynamicMetadataNumber mocks base method.
func (m *MockNetworkFilterHandle) SetDynamicMetadataNumber(metadataNamespace, key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDynamicMetadataNumber", metadataNamespace, key, value)
}

// SetDynamicMetadataNumber indicates an expected call of SetDynamicMetadataNumber.
func (mr *MockNetworkFilterHandleMockRecorder) SetDynamicMetadataNumber(metadataNamespace, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDynamicMetadataNumber", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetDynamicMetadataNumber), metadataNamespace, key, value)
}

// SetDynamicMetadataString mocks base method.
func (m *MockNetworkFilterHandle) SetDynamicMetadataString(metadataNamespace, key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDynamicMetadataString", metadataNamespace, key, value)
}

// SetDynamicMetadataString indicates an expected call of SetDynamicMetadataString.
func (mr *MockNetworkFilterHandleMockRecorder) SetDynamicMetadataString(metadataNamespace, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDynamicMetadataString", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetDynamicMetadataString), metadataNamespace, key, value)
}

// SetFilterState mocks base method.
func (m *MockNetworkFilterHandle) SetFilterState(key string, value []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFilterState", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetFilterState indicates an expected call of SetFilterState.
func (mr *MockNetworkFilterHandleMockRecorder) SetFilterState(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFilterState", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetFilterState), key, value)
}

// SetFilterStateTyped mocks base method.
func (m *MockNetworkFilterHandle) SetFilterStateTyped(key string, value []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFilterStateTyped", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetFilterStateTyped indicates an expected call of SetFilterStateTyped.
func (mr *MockNetworkFilterHandleMockRecorder) SetFilterStateTyped(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFilterStateTyped", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetFilterStateTyped), key, value)
}

// SetGauge mocks base method.
func (m *MockNetworkFilterHandle) SetGauge(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockNetworkFilterHandleMockRecorder) SetGauge(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetGauge), id, value)
}

// SetSocketOptionBytes mocks base method.
func (m *MockNetworkFilterHandle) SetSocketOptionBytes(level, name int64, state shared.SocketOptionState, value []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSocketOptionBytes", level, name, state, value)
}

// SetSocketOptionBytes indicates an expected call of SetSocketOptionBytes.
func (mr *MockNetworkFilterHandleMockRecorder) SetSocketOptionBytes(level, name, state, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSocketOptionBytes", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetSocketOptionBytes), level, name, state, value)
}

// SetSocketOptionInt mocks base method.
func (m *MockNetworkFilterHandle) SetSocketOptionInt(level, name int64, state shared.SocketOptionState, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSocketOptionInt", level, name, state, value)
}

// SetSocketOptionInt indicates an expected call of SetSocketOptionInt.
func (mr *MockNetworkFilterHandleMockRecorder) SetSocketOptionInt(level, name, state, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSocketOptionInt", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetSocketOptionInt), level, name, state, value)
}

// StartUpstreamSecureTransport mocks base method.
func (m *MockNetworkFilterHandle) StartUpstreamSecureTransport() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartUpstreamSecureTransport")
	ret0, _ := ret[0].(bool)
	return ret0
}

// StartUpstreamSecureTransport indicates an expected call of StartUpstreamSecureTransport.
func (mr *MockNetworkFilterHandleMockRecorder) StartUpstreamSecureTransport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartUpstreamSecureTransport", reflect.TypeOf((*MockNetworkFilterHandle)(nil).StartUpstreamSecureTransport))
}

// Write mocks base method.
func (m *MockNetworkFilterHandle) Write(data []byte, endOfStream bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write", data, endOfStream)
}

// Write indicates an expected call of Write.
func (mr *MockNetworkFilterHandleMockRecorder) Write(data, endOfStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockNetworkFilterHandle)(nil).Write), data, endOfStream)
}
