// Code generated by MockGen. DO NOT EDIT.
// Source: network_base.go
//
// Generated by this command:
//
//	mockgen -source=network_base.go -destination=mocks/mock_network_base.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	shared "github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkBuffer is a mock of NetworkBuffer interface.
type MockNetworkBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkBufferMockRecorder
	isgomock struct{}
}

// MockNetworkBufferMockRecorder is the mock recorder for MockNetworkBuffer.
type MockNetworkBufferMockRecorder struct {
	mock *MockNetworkBuffer
}

// NewMockNetworkBuffer creates a new mock instance.
func NewMockNetworkBuffer(ctrl *gomock.Controller) *MockNetworkBuffer {
	mock := &MockNetworkBuffer{ctrl: ctrl}
	mock.recorder = &MockNetworkBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkBuffer) EXPECT() *MockNetworkBufferMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockNetworkBuffer) Append(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockNetworkBufferMockRecorder) Append(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockNetworkBuffer)(nil).Append), data)
}

// Drain mocks base method.
func (m *MockNetworkBuffer) Drain(numBytes uint64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drain", numBytes)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Drain indicates an expected call of Drain.
func (mr *MockNetworkBufferMockRecorder) Drain(numBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drain", reflect.TypeOf((*MockNetworkBuffer)(nil).Drain), numBytes)
}

// GetChunks mocks base method.
func (m *MockNetworkBuffer) GetChunks() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunks")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetChunks indicates an expected call of GetChunks.
func (mr *MockNetworkBufferMockRecorder) GetChunks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunks", reflect.TypeOf((*MockNetworkBuffer)(nil).GetChunks))
}

// GetSize mocks base method.
func (m *MockNetworkBuffer) GetSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetSize indicates an expected call of GetSize.
func (mr *MockNetworkBufferMockRecorder) GetSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSize", reflect.TypeOf((*MockNetworkBuffer)(nil).GetSize))
}

// Prepend mocks base method.
func (m *MockNetworkBuffer) Prepend(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepend", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Prepend indicates an expected call of Prepend.
func (mr *MockNetworkBufferMockRecorder) Prepend(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepend", reflect.TypeOf((*MockNetworkBuffer)(nil).Prepend), data)
}

// MockNetworkFilterHandle is a mock of NetworkFilterHandle interface.
type MockNetworkFilterHandle struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterHandleMockRecorder
	isgomock struct{}
}

// MockNetworkFilterHandleMockRecorder is the mock recorder for MockNetworkFilterHandle.
type MockNetworkFilterHandleMockRecorder struct {
	mock *MockNetworkFilterHandle
}

// NewMockNetworkFilterHandle creates a new mock instance.
func NewMockNetworkFilterHandle(ctrl *gomock.Controller) *MockNetworkFilterHandle {
	mock := &MockNetworkFilterHandle{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilterHandle) EXPECT() *MockNetworkFilterHandleMockRecorder {
	return m.recorder
}

// AboveHighWatermark mocks base method.
func (m *MockNetworkFilterHandle) AboveHighWatermark() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AboveHighWatermark")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AboveHighWatermark indicates an expected call of AboveHighWatermark.
func (mr *MockNetworkFilterHandleMockRecorder) AboveHighWatermark() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AboveHighWatermark", reflect.TypeOf((*MockNetworkFilterHandle)(nil).AboveHighWatermark))
}

// Close mocks base method.
func (m *MockNetworkFilterHandle) Close(closeType shared.NetworkConnectionCloseType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", closeType)
}

// Close indicates an expected call of Close.
func (mr *MockNetworkFilterHandleMockRecorder) Close(closeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNetworkFilterHandle)(nil).Close), closeType)
}

// CloseWithDetails mocks base method.
func (m *MockNetworkFilterHandle) CloseWithDetails(closeType shared.NetworkConnectionCloseType, details string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseWithDetails", closeType, details)
}

// CloseWithDetails indicates an expected call of CloseWithDetails.
func (mr *MockNetworkFilterHandleMockRecorder) CloseWithDetails(closeType, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWithDetails", reflect.TypeOf((*MockNetworkFilterHandle)(nil).CloseWithDetails), closeType, details)
}

// ContinueReading mocks base method.
func (m *MockNetworkFilterHandle) ContinueReading() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ContinueReading")
}

// ContinueReading indicates an expected call of ContinueReading.
func (mr *MockNetworkFilterHandleMockRecorder) ContinueReading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueReading", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ContinueReading))
}

// DecrementGaugeValue mocks base method.
func (m *MockNetworkFilterHandle) DecrementGaugeValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementGaugeValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// DecrementGaugeValue indicates an expected call of DecrementGaugeValue.
func (mr *MockNetworkFilterHandleMockRecorder) DecrementGaugeValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementGaugeValue", reflect.TypeOf((*MockNetworkFilterHandle)(nil).DecrementGaugeValue), id, value)
}

// DisableClose mocks base method.
func (m *MockNetworkFilterHandle) DisableClose(disabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisableClose", disabled)
}

// DisableClose indicates an expected call of DisableClose.
func (mr *MockNetworkFilterHandleMockRecorder) DisableClose(disabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableClose", reflect.TypeOf((*MockNetworkFilterHandle)(nil).DisableClose), disabled)
}

// EnableHalfClose mocks base method.
func (m *MockNetworkFilterHandle) EnableHalfClose(enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableHalfClose", enabled)
}

// EnableHalfClose indicates an expected call of EnableHalfClose.
func (mr *MockNetworkFilterHandleMockRecorder) EnableHalfClose(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableHalfClose", reflect.TypeOf((*MockNetworkFilterHandle)(nil).EnableHalfClose), enabled)
}

// GetBufferLimit mocks base method.
func (m *MockNetworkFilterHandle) GetBufferLimit() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBufferLimit")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetBufferLimit indicates an expected call of GetBufferLimit.
func (mr *MockNetworkFilterHandleMockRecorder) GetBufferLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBufferLimit", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetBufferLimit))
}

// GetClusterHostCounts mocks base method.
func (m *MockNetworkFilterHandle) GetClusterHostCounts(cluster string, priority uint32) (shared.ClusterHostCounts, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterHostCounts", cluster, priority)
	ret0, _ := ret[0].(shared.ClusterHostCounts)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClusterHostCounts indicates an expected call of GetClusterHostCounts.
func (mr *MockNetworkFilterHandleMockRecorder) GetClusterHostCounts(cluster, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterHostCounts", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetClusterHostCounts), cluster, priority)
}

// GetConnectionID mocks base method.
func (m *MockNetworkFilterHandle) GetConnectionID() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionID")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetConnectionID indicates an expected call of GetConnectionID.
func (mr *MockNetworkFilterHandleMockRecorder) GetConnectionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionID", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetConnectionID))
}

// GetConnectionState mocks base method.
func (m *MockNetworkFilterHandle) GetConnectionState() shared.NetworkConnectionState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionState")
	ret0, _ := ret[0].(shared.NetworkConnectionState)
	return ret0
}

// GetConnectionState indicates an expected call of GetConnectionState.
func (mr *MockNetworkFilterHandleMockRecorder) GetConnectionState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionState", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetConnectionState))
}

// GetDirectRemoteAddress mocks base method.
func (m *MockNetworkFilterHandle) GetDirectRemoteAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectRemoteAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetDirectRemoteAddress indicates an expected call of GetDirectRemoteAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetDirectRemoteAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectRemoteAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetDirectRemoteAddress))
}

// GetFilterState mocks base method.
func (m *MockNetworkFilterHandle) GetFilterState(key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterState", key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilterState indicates an expected call of GetFilterState.
func (mr *MockNetworkFilterHandleMockRecorder) GetFilterState(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterState", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetFilterState), key)
}

// GetFilterStateTyped mocks base method.
func (m *MockNetworkFilterHandle) GetFilterStateTyped(key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterStateTyped", key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilterStateTyped indicates an expected call of GetFilterStateTyped.
func (mr *MockNetworkFilterHandleMockRecorder) GetFilterStateTyped(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterStateTyped", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetFilterStateTyped), key)
}

// GetLocalAddress mocks base method.
func (m *MockNetworkFilterHandle) GetLocalAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetLocalAddress indicates an expected call of GetLocalAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetLocalAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetLocalAddress))
}

// GetMetadataBool mocks base method.
func (m *MockNetworkFilterHandle) GetMetadataBool(metadataNamespace, key string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataBool", metadataNamespace, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetadataBool indicates an expected call of GetMetadataBool.
func (mr *MockNetworkFilterHandleMockRecorder) GetMetadataBool(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataBool", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetMetadataBool), metadataNamespace, key)
}

// GetMetadataNumber mocks base method.
func (m *MockNetworkFilterHandle) GetMetadataNumber(metadataNamespace, key string) (float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataNumber", metadataNamespace, key)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetadataNumber indicates an expected call of GetMetadataNumber.
func (mr *MockNetworkFilterHandleMockRecorder) GetMetadataNumber(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataNumber", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetMetadataNumber), metadataNamespace, key)
}

// GetMetadataString mocks base method.
func (m *MockNetworkFilterHandle) GetMetadataString(metadataNamespace, key string) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataString", metadataNamespace, key)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMetadataString indicates an expected call of GetMetadataString.
func (mr *MockNetworkFilterHandleMockRecorder) GetMetadataString(metadataNamespace, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataString", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetMetadataString), metadataNamespace, key)
}

// GetRemoteAddress mocks base method.
func (m *MockNetworkFilterHandle) GetRemoteAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetRemoteAddress indicates an expected call of GetRemoteAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetRemoteAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetRemoteAddress))
}

// GetRequestedServerName mocks base method.
func (m *MockNetworkFilterHandle) GetRequestedServerName() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedServerName")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRequestedServerName indicates an expected call of GetRequestedServerName.
func (mr *MockNetworkFilterHandleMockRecorder) GetRequestedServerName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedServerName", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetRequestedServerName))
}

// GetSSLDNSSANs mocks base method.
func (m *MockNetworkFilterHandle) GetSSLDNSSANs() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLDNSSANs")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetSSLDNSSANs indicates an expected call of GetSSLDNSSANs.
func (mr *MockNetworkFilterHandleMockRecorder) GetSSLDNSSANs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLDNSSANs", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSSLDNSSANs))
}

// GetSSLSubject mocks base method.
func (m *MockNetworkFilterHandle) GetSSLSubject() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLSubject")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSSLSubject indicates an expected call of GetSSLSubject.
func (mr *MockNetworkFilterHandleMockRecorder) GetSSLSubject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLSubject", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSSLSubject))
}

// GetSSLURISANs mocks base method.
func (m *MockNetworkFilterHandle) GetSSLURISANs() []shared.UnsafeEnvoyBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSLURISANs")
	ret0, _ := ret[0].([]shared.UnsafeEnvoyBuffer)
	return ret0
}

// GetSSLURISANs indicates an expected call of GetSSLURISANs.
func (mr *MockNetworkFilterHandleMockRecorder) GetSSLURISANs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSLURISANs", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSSLURISANs))
}

// GetScheduler mocks base method.
func (m *MockNetworkFilterHandle) GetScheduler() shared.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler")
	ret0, _ := ret[0].(shared.Scheduler)
	return ret0
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockNetworkFilterHandleMockRecorder) GetScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetScheduler))
}

// GetSocketOptionBytes mocks base method.
func (m *MockNetworkFilterHandle) GetSocketOptionBytes(level, name int64, state shared.SocketOptionState) (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptionBytes", level, name, state)
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSocketOptionBytes indicates an expected call of GetSocketOptionBytes.
func (mr *MockNetworkFilterHandleMockRecorder) GetSocketOptionBytes(level, name, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptionBytes", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSocketOptionBytes), level, name, state)
}

// GetSocketOptionInt mocks base method.
func (m *MockNetworkFilterHandle) GetSocketOptionInt(level, name int64, state shared.SocketOptionState) (int64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptionInt", level, name, state)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSocketOptionInt indicates an expected call of GetSocketOptionInt.
func (mr *MockNetworkFilterHandleMockRecorder) GetSocketOptionInt(level, name, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptionInt", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSocketOptionInt), level, name, state)
}

// GetSocketOptions mocks base method.
func (m *MockNetworkFilterHandle) GetSocketOptions() []shared.SocketOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketOptions")
	ret0, _ := ret[0].([]shared.SocketOption)
	return ret0
}

// GetSocketOptions indicates an expected call of GetSocketOptions.
func (mr *MockNetworkFilterHandleMockRecorder) GetSocketOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketOptions", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetSocketOptions))
}

// GetUpstreamHostAddress mocks base method.
func (m *MockNetworkFilterHandle) GetUpstreamHostAddress() (shared.UnsafeEnvoyBuffer, uint32, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpstreamHostAddress")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetUpstreamHostAddress indicates an expected call of GetUpstreamHostAddress.
func (mr *MockNetworkFilterHandleMockRecorder) GetUpstreamHostAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpstreamHostAddress", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetUpstreamHostAddress))
}

// GetUpstreamHostCluster mocks base method.
func (m *MockNetworkFilterHandle) GetUpstreamHostCluster() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpstreamHostCluster")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUpstreamHostCluster indicates an expected call of GetUpstreamHostCluster.
func (mr *MockNetworkFilterHandleMockRecorder) GetUpstreamHostCluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpstreamHostCluster", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetUpstreamHostCluster))
}

// GetUpstreamHostHostname mocks base method.
func (m *MockNetworkFilterHandle) GetUpstreamHostHostname() (shared.UnsafeEnvoyBuffer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpstreamHostHostname")
	ret0, _ := ret[0].(shared.UnsafeEnvoyBuffer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUpstreamHostHostname indicates an expected call of GetUpstreamHostHostname.
func (mr *MockNetworkFilterHandleMockRecorder) GetUpstreamHostHostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpstreamHostHostname", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetUpstreamHostHostname))
}

// GetWorkerIndex mocks base method.
func (m *MockNetworkFilterHandle) GetWorkerIndex() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerIndex")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetWorkerIndex indicates an expected call of GetWorkerIndex.
func (mr *MockNetworkFilterHandleMockRecorder) GetWorkerIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerIndex", reflect.TypeOf((*MockNetworkFilterHandle)(nil).GetWorkerIndex))
}

// HasUpstreamHost mocks base method.
func (m *MockNetworkFilterHandle) HasUpstreamHost() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUpstreamHost")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasUpstreamHost indicates an expected call of HasUpstreamHost.
func (mr *MockNetworkFilterHandleMockRecorder) HasUpstreamHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUpstreamHost", reflect.TypeOf((*MockNetworkFilterHandle)(nil).HasUpstreamHost))
}

// HttpCallout mocks base method.
func (m *MockNetworkFilterHandle) HttpCallout(cluster string, headers [][2]string, body []byte, timeoutMs uint64, cb shared.HttpCalloutCallback) (shared.HttpCalloutInitResult, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HttpCallout", cluster, headers, body, timeoutMs, cb)
	ret0, _ := ret[0].(shared.HttpCalloutInitResult)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// HttpCallout indicates an expected call of HttpCallout.
func (mr *MockNetworkFilterHandleMockRecorder) HttpCallout(cluster, headers, body, timeoutMs, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HttpCallout", reflect.TypeOf((*MockNetworkFilterHandle)(nil).HttpCallout), cluster, headers, body, timeoutMs, cb)
}

// IncrementCounterValue mocks base method.
func (m *MockNetworkFilterHandle) IncrementCounterValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounterValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementCounterValue indicates an expected call of IncrementCounterValue.
func (mr *MockNetworkFilterHandleMockRecorder) IncrementCounterValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounterValue", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IncrementCounterValue), id, value)
}

// IncrementGaugeValue mocks base method.
func (m *MockNetworkFilterHandle) IncrementGaugeValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementGaugeValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementGaugeValue indicates an expected call of IncrementGaugeValue.
func (mr *MockNetworkFilterHandleMockRecorder) IncrementGaugeValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementGaugeValue", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IncrementGaugeValue), id, value)
}

// InjectReadData mocks base method.
func (m *MockNetworkFilterHandle) InjectReadData(data []byte, endStream bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectReadData", data, endStream)
}

// InjectReadData indicates an expected call of InjectReadData.
func (mr *MockNetworkFilterHandleMockRecorder) InjectReadData(data, endStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectReadData", reflect.TypeOf((*MockNetworkFilterHandle)(nil).InjectReadData), data, endStream)
}

// InjectWriteData mocks base method.
func (m *MockNetworkFilterHandle) InjectWriteData(data []byte, endStream bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectWriteData", data, endStream)
}

// InjectWriteData indicates an expected call of InjectWriteData.
func (mr *MockNetworkFilterHandleMockRecorder) InjectWriteData(data, endStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectWriteData", reflect.TypeOf((*MockNetworkFilterHandle)(nil).InjectWriteData), data, endStream)
}

// IsHalfCloseEnabled mocks base method.
func (m *MockNetworkFilterHandle) IsHalfCloseEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHalfCloseEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHalfCloseEnabled indicates an expected call of IsHalfCloseEnabled.
func (mr *MockNetworkFilterHandleMockRecorder) IsHalfCloseEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHalfCloseEnabled", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IsHalfCloseEnabled))
}

// IsSSL mocks base method.
func (m *MockNetworkFilterHandle) IsSSL() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSSL")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSSL indicates an expected call of IsSSL.
func (mr *MockNetworkFilterHandleMockRecorder) IsSSL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSSL", reflect.TypeOf((*MockNetworkFilterHandle)(nil).IsSSL))
}

// Log mocks base method.
func (m *MockNetworkFilterHandle) Log(level shared.LogLevel, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{level, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockNetworkFilterHandleMockRecorder) Log(level, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockNetworkFilterHandle)(nil).Log), varargs...)
}

// ReadBuffer mocks base method.
func (m *MockNetworkFilterHandle) ReadBuffer() shared.NetworkBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBuffer")
	ret0, _ := ret[0].(shared.NetworkBuffer)
	return ret0
}

// ReadBuffer indicates an expected call of ReadBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) ReadBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ReadBuffer))
}

// ReadDisable mocks base method.
func (m *MockNetworkFilterHandle) ReadDisable(disable bool) shared.NetworkReadDisableStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDisable", disable)
	ret0, _ := ret[0].(shared.NetworkReadDisableStatus)
	return ret0
}

// ReadDisable indicates an expected call of ReadDisable.
func (mr *MockNetworkFilterHandleMockRecorder) ReadDisable(disable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDisable", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ReadDisable), disable)
}

// ReadEnabled mocks base method.
func (m *MockNetworkFilterHandle) ReadEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReadEnabled indicates an expected call of ReadEnabled.
func (mr *MockNetworkFilterHandleMockRecorder) ReadEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEnabled", reflect.TypeOf((*MockNetworkFilterHandle)(nil).ReadEnabled))
}

// RecordHistogramValue mocks base method.
func (m *MockNetworkFilterHandle) RecordHistogramValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHistogramValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// RecordHistogramValue indicates an expected call of RecordHistogramValue.
func (mr *MockNetworkFilterHandleMockRecorder) RecordHistogramValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHistogramValue", reflect.TypeOf((*MockNetworkFilterHandle)(nil).RecordHistogramValue), id, value)
}

// SetBufferLimits mocks base method.
func (m *MockNetworkFilterHandle) SetBufferLimits(limit uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBufferLimits", limit)
}

// SetBufferLimits indicates an expected call of SetBufferLimits.
func (mr *MockNetworkFilterHandleMockRecorder) SetBufferLimits(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBufferLimits", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetBufferLimits), limit)
}

// SetFilterState mocks base method.
func (m *MockNetworkFilterHandle) SetFilterState(key string, value []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFilterState", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetFilterState indicates an expected call of SetFilterState.
func (mr *MockNetworkFilterHandleMockRecorder) SetFilterState(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFilterState", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetFilterState), key, value)
}

// SetFilterStateTyped mocks base method.
func (m *MockNetworkFilterHandle) SetFilterStateTyped(key string, value []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFilterStateTyped", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetFilterStateTyped indicates an expected call of SetFilterStateTyped.
func (mr *MockNetworkFilterHandleMockRecorder) SetFilterStateTyped(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFilterStateTyped", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetFilterStateTyped), key, value)
}

// SetGaugeValue mocks base method.
func (m *MockNetworkFilterHandle) SetGaugeValue(id shared.MetricID, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGaugeValue", id, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// SetGaugeValue indicates an expected call of SetGaugeValue.
func (mr *MockNetworkFilterHandleMockRecorder) SetGaugeValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGaugeValue", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetGaugeValue), id, value)
}

// SetMetadata mocks base method.
func (m *MockNetworkFilterHandle) SetMetadata(metadataNamespace, key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetadata", metadataNamespace, key, value)
}

// SetMetadata indicates an expected call of SetMetadata.
func (mr *MockNetworkFilterHandleMockRecorder) SetMetadata(metadataNamespace, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetadata", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetMetadata), metadataNamespace, key, value)
}

// SetSocketOptionBytes mocks base method.
func (m *MockNetworkFilterHandle) SetSocketOptionBytes(level, name int64, state shared.SocketOptionState, value []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSocketOptionBytes", level, name, state, value)
}

// SetSocketOptionBytes indicates an expected call of SetSocketOptionBytes.
func (mr *MockNetworkFilterHandleMockRecorder) SetSocketOptionBytes(level, name, state, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSocketOptionBytes", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetSocketOptionBytes), level, name, state, value)
}

// SetSocketOptionInt mocks base method.
func (m *MockNetworkFilterHandle) SetSocketOptionInt(level, name int64, state shared.SocketOptionState, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSocketOptionInt", level, name, state, value)
}

// SetSocketOptionInt indicates an expected call of SetSocketOptionInt.
func (mr *MockNetworkFilterHandleMockRecorder) SetSocketOptionInt(level, name, state, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSocketOptionInt", reflect.TypeOf((*MockNetworkFilterHandle)(nil).SetSocketOptionInt), level, name, state, value)
}

// StartUpstreamSecureTransport mocks base method.
func (m *MockNetworkFilterHandle) StartUpstreamSecureTransport() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartUpstreamSecureTransport")
	ret0, _ := ret[0].(bool)
	return ret0
}

// StartUpstreamSecureTransport indicates an expected call of StartUpstreamSecureTransport.
func (mr *MockNetworkFilterHandleMockRecorder) StartUpstreamSecureTransport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartUpstreamSecureTransport", reflect.TypeOf((*MockNetworkFilterHandle)(nil).StartUpstreamSecureTransport))
}

// Write mocks base method.
func (m *MockNetworkFilterHandle) Write(data []byte, endStream bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write", data, endStream)
}

// Write indicates an expected call of Write.
func (mr *MockNetworkFilterHandleMockRecorder) Write(data, endStream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockNetworkFilterHandle)(nil).Write), data, endStream)
}

// WriteBuffer mocks base method.
func (m *MockNetworkFilterHandle) WriteBuffer() shared.NetworkBuffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBuffer")
	ret0, _ := ret[0].(shared.NetworkBuffer)
	return ret0
}

// WriteBuffer indicates an expected call of WriteBuffer.
func (mr *MockNetworkFilterHandleMockRecorder) WriteBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBuffer", reflect.TypeOf((*MockNetworkFilterHandle)(nil).WriteBuffer))
}

// MockNetworkFilterConfigHandle is a mock of NetworkFilterConfigHandle interface.
type MockNetworkFilterConfigHandle struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkFilterConfigHandleMockRecorder
	isgomock struct{}
}

// MockNetworkFilterConfigHandleMockRecorder is the mock recorder for MockNetworkFilterConfigHandle.
type MockNetworkFilterConfigHandleMockRecorder struct {
	mock *MockNetworkFilterConfigHandle
}

// NewMockNetworkFilterConfigHandle creates a new mock instance.
func NewMockNetworkFilterConfigHandle(ctrl *gomock.Controller) *MockNetworkFilterConfigHandle {
	mock := &MockNetworkFilterConfigHandle{ctrl: ctrl}
	mock.recorder = &MockNetworkFilterConfigHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkFilterConfigHandle) EXPECT() *MockNetworkFilterConfigHandleMockRecorder {
	return m.recorder
}

// DefineCounter mocks base method.
func (m *MockNetworkFilterConfigHandle) DefineCounter(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineCounter", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineCounter indicates an expected call of DefineCounter.
func (mr *MockNetworkFilterConfigHandleMockRecorder) DefineCounter(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineCounter", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).DefineCounter), name)
}

// DefineGauge mocks base method.
func (m *MockNetworkFilterConfigHandle) DefineGauge(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineGauge", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineGauge indicates an expected call of DefineGauge.
func (mr *MockNetworkFilterConfigHandleMockRecorder) DefineGauge(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineGauge", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).DefineGauge), name)
}

// DefineHistogram mocks base method.
func (m *MockNetworkFilterConfigHandle) DefineHistogram(name string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineHistogram", name)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineHistogram indicates an expected call of DefineHistogram.
func (mr *MockNetworkFilterConfigHandleMockRecorder) DefineHistogram(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineHistogram", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).DefineHistogram), name)
}

// GetScheduler mocks base method.
func (m *MockNetworkFilterConfigHandle) GetScheduler() shared.Scheduler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduler")
	ret0, _ := ret[0].(shared.Scheduler)
	return ret0
}

// GetScheduler indicates an expected call of GetScheduler.
func (mr *MockNetworkFilterConfigHandleMockRecorder) GetScheduler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduler", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).GetScheduler))
}

// Log mocks base method.
func (m *MockNetworkFilterConfigHandle) Log(level shared.LogLevel, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{level, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockNetworkFilterConfigHandleMockRecorder) Log(level, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockNetworkFilterConfigHandle)(nil).Log), varargs...)
}
