// Code generated by MockGen. DO NOT EDIT.
// Source: program.go
//
// Generated by this command:
//
//	mockgen -source=program.go -destination=mocks/mock_program.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	unsafe "unsafe"

	shared "github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockProgramHandle is a mock of ProgramHandle interface.
type MockProgramHandle struct {
	ctrl     *gomock.Controller
	recorder *MockProgramHandleMockRecorder
	isgomock struct{}
}

// MockProgramHandleMockRecorder is the mock recorder for MockProgramHandle.
type MockProgramHandleMockRecorder struct {
	mock *MockProgramHandle
}

// NewMockProgramHandle creates a new mock instance.
func NewMockProgramHandle(ctrl *gomock.Controller) *MockProgramHandle {
	mock := &MockProgramHandle{ctrl: ctrl}
	mock.recorder = &MockProgramHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgramHandle) EXPECT() *MockProgramHandleMockRecorder {
	return m.recorder
}

// GetConcurrency mocks base method.
func (m *MockProgramHandle) GetConcurrency() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConcurrency")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetConcurrency indicates an expected call of GetConcurrency.
func (mr *MockProgramHandleMockRecorder) GetConcurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConcurrency", reflect.TypeOf((*MockProgramHandle)(nil).GetConcurrency))
}

// GetFunction mocks base method.
func (m *MockProgramHandle) GetFunction(key string) (unsafe.Pointer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunction", key)
	ret0, _ := ret[0].(unsafe.Pointer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFunction indicates an expected call of GetFunction.
func (mr *MockProgramHandleMockRecorder) GetFunction(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunction", reflect.TypeOf((*MockProgramHandle)(nil).GetFunction), key)
}

// GetSharedData mocks base method.
func (m *MockProgramHandle) GetSharedData(key string) (unsafe.Pointer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedData", key)
	ret0, _ := ret[0].(unsafe.Pointer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSharedData indicates an expected call of GetSharedData.
func (mr *MockProgramHandleMockRecorder) GetSharedData(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedData", reflect.TypeOf((*MockProgramHandle)(nil).GetSharedData), key)
}

// IsValidationMode mocks base method.
func (m *MockProgramHandle) IsValidationMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidationMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidationMode indicates an expected call of IsValidationMode.
func (mr *MockProgramHandleMockRecorder) IsValidationMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidationMode", reflect.TypeOf((*MockProgramHandle)(nil).IsValidationMode))
}

// Log mocks base method.
func (m *MockProgramHandle) Log(level shared.LogLevel, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{level, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockProgramHandleMockRecorder) Log(level, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockProgramHandle)(nil).Log), varargs...)
}

// RegisterFunction mocks base method.
func (m *MockProgramHandle) RegisterFunction(key string, fnPtr unsafe.Pointer) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterFunction", key, fnPtr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RegisterFunction indicates an expected call of RegisterFunction.
func (mr *MockProgramHandleMockRecorder) RegisterFunction(key, fnPtr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterFunction", reflect.TypeOf((*MockProgramHandle)(nil).RegisterFunction), key, fnPtr)
}

// RegisterSharedData mocks base method.
func (m *MockProgramHandle) RegisterSharedData(key string, dataPtr unsafe.Pointer) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSharedData", key, dataPtr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RegisterSharedData indicates an expected call of RegisterSharedData.
func (mr *MockProgramHandleMockRecorder) RegisterSharedData(key, dataPtr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSharedData", reflect.TypeOf((*MockProgramHandle)(nil).RegisterSharedData), key, dataPtr)
}
