// Code generated by MockGen. DO NOT EDIT.
// Source: dns_resolver.go
//
// Generated by this command:
//
//	mockgen -source=dns_resolver.go -destination=mocks/mock_dns_resolver.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	shared "github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockDnsResolver is a mock of DnsResolver interface.
type MockDnsResolver struct {
	ctrl     *gomock.Controller
	recorder *MockDnsResolverMockRecorder
	isgomock struct{}
}

// MockDnsResolverMockRecorder is the mock recorder for MockDnsResolver.
type MockDnsResolverMockRecorder struct {
	mock *MockDnsResolver
}

// NewMockDnsResolver creates a new mock instance.
func NewMockDnsResolver(ctrl *gomock.Controller) *MockDnsResolver {
	mock := &MockDnsResolver{ctrl: ctrl}
	mock.recorder = &MockDnsResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsResolver) EXPECT() *MockDnsResolverMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockDnsResolver) Cancel(query any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", query)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockDnsResolverMockRecorder) Cancel(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockDnsResolver)(nil).Cancel), query)
}

// OnDestroy mocks base method.
func (m *MockDnsResolver) OnDestroy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDestroy")
}

// OnDestroy indicates an expected call of OnDestroy.
func (mr *MockDnsResolverMockRecorder) OnDestroy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDestroy", reflect.TypeOf((*MockDnsResolver)(nil).OnDestroy))
}

// ResetNetworking mocks base method.
func (m *MockDnsResolver) ResetNetworking() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetNetworking")
}

// ResetNetworking indicates an expected call of ResetNetworking.
func (mr *MockDnsResolverMockRecorder) ResetNetworking() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetNetworking", reflect.TypeOf((*MockDnsResolver)(nil).ResetNetworking))
}

// Resolve mocks base method.
func (m *MockDnsResolver) Resolve(handle shared.DnsResolverConfigHandle, dnsName string, family shared.DnsLookupFamily, queryID uint64) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", handle, dnsName, family, queryID)
	ret0, _ := ret[0].(any)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockDnsResolverMockRecorder) Resolve(handle, dnsName, family, queryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockDnsResolver)(nil).Resolve), handle, dnsName, family, queryID)
}

// MockDnsResolverFactory is a mock of DnsResolverFactory interface.
type MockDnsResolverFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDnsResolverFactoryMockRecorder
	isgomock struct{}
}

// MockDnsResolverFactoryMockRecorder is the mock recorder for MockDnsResolverFactory.
type MockDnsResolverFactoryMockRecorder struct {
	mock *MockDnsResolverFactory
}

// NewMockDnsResolverFactory creates a new mock instance.
func NewMockDnsResolverFactory(ctrl *gomock.Controller) *MockDnsResolverFactory {
	mock := &MockDnsResolverFactory{ctrl: ctrl}
	mock.recorder = &MockDnsResolverFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsResolverFactory) EXPECT() *MockDnsResolverFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDnsResolverFactory) Create(handle shared.DnsResolverConfigHandle) shared.DnsResolver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", handle)
	ret0, _ := ret[0].(shared.DnsResolver)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDnsResolverFactoryMockRecorder) Create(handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDnsResolverFactory)(nil).Create), handle)
}

// OnDestroy mocks base method.
func (m *MockDnsResolverFactory) OnDestroy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDestroy")
}

// OnDestroy indicates an expected call of OnDestroy.
func (mr *MockDnsResolverFactoryMockRecorder) OnDestroy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDestroy", reflect.TypeOf((*MockDnsResolverFactory)(nil).OnDestroy))
}

// MockDnsResolverConfigFactory is a mock of DnsResolverConfigFactory interface.
type MockDnsResolverConfigFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDnsResolverConfigFactoryMockRecorder
	isgomock struct{}
}

// MockDnsResolverConfigFactoryMockRecorder is the mock recorder for MockDnsResolverConfigFactory.
type MockDnsResolverConfigFactoryMockRecorder struct {
	mock *MockDnsResolverConfigFactory
}

// NewMockDnsResolverConfigFactory creates a new mock instance.
func NewMockDnsResolverConfigFactory(ctrl *gomock.Controller) *MockDnsResolverConfigFactory {
	mock := &MockDnsResolverConfigFactory{ctrl: ctrl}
	mock.recorder = &MockDnsResolverConfigFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsResolverConfigFactory) EXPECT() *MockDnsResolverConfigFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDnsResolverConfigFactory) Create(handle shared.DnsResolverConfigHandle, unparsedConfig []byte) (shared.DnsResolverFactory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", handle, unparsedConfig)
	ret0, _ := ret[0].(shared.DnsResolverFactory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDnsResolverConfigFactoryMockRecorder) Create(handle, unparsedConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDnsResolverConfigFactory)(nil).Create), handle, unparsedConfig)
}

// MockDnsResolverConfigHandle is a mock of DnsResolverConfigHandle interface.
type MockDnsResolverConfigHandle struct {
	ctrl     *gomock.Controller
	recorder *MockDnsResolverConfigHandleMockRecorder
	isgomock struct{}
}

// MockDnsResolverConfigHandleMockRecorder is the mock recorder for MockDnsResolverConfigHandle.
type MockDnsResolverConfigHandleMockRecorder struct {
	mock *MockDnsResolverConfigHandle
}

// NewMockDnsResolverConfigHandle creates a new mock instance.
func NewMockDnsResolverConfigHandle(ctrl *gomock.Controller) *MockDnsResolverConfigHandle {
	mock := &MockDnsResolverConfigHandle{ctrl: ctrl}
	mock.recorder = &MockDnsResolverConfigHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsResolverConfigHandle) EXPECT() *MockDnsResolverConfigHandleMockRecorder {
	return m.recorder
}

// DecrementGauge mocks base method.
func (m *MockDnsResolverConfigHandle) DecrementGauge(id shared.MetricID, labelValues []string, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementGauge", id, labelValues, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// DecrementGauge indicates an expected call of DecrementGauge.
func (mr *MockDnsResolverConfigHandleMockRecorder) DecrementGauge(id, labelValues, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementGauge", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).DecrementGauge), id, labelValues, value)
}

// DefineCounter mocks base method.
func (m *MockDnsResolverConfigHandle) DefineCounter(name string, labelNames []string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineCounter", name, labelNames)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineCounter indicates an expected call of DefineCounter.
func (mr *MockDnsResolverConfigHandleMockRecorder) DefineCounter(name, labelNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineCounter", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).DefineCounter), name, labelNames)
}

// DefineGauge mocks base method.
func (m *MockDnsResolverConfigHandle) DefineGauge(name string, labelNames []string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineGauge", name, labelNames)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineGauge indicates an expected call of DefineGauge.
func (mr *MockDnsResolverConfigHandleMockRecorder) DefineGauge(name, labelNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineGauge", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).DefineGauge), name, labelNames)
}

// DefineHistogram mocks base method.
func (m *MockDnsResolverConfigHandle) DefineHistogram(name string, labelNames []string) (shared.MetricID, shared.MetricsResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefineHistogram", name, labelNames)
	ret0, _ := ret[0].(shared.MetricID)
	ret1, _ := ret[1].(shared.MetricsResult)
	return ret0, ret1
}

// DefineHistogram indicates an expected call of DefineHistogram.
func (mr *MockDnsResolverConfigHandleMockRecorder) DefineHistogram(name, labelNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefineHistogram", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).DefineHistogram), name, labelNames)
}

// IncrementCounter mocks base method.
func (m *MockDnsResolverConfigHandle) IncrementCounter(id shared.MetricID, labelValues []string, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", id, labelValues, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockDnsResolverConfigHandleMockRecorder) IncrementCounter(id, labelValues, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).IncrementCounter), id, labelValues, value)
}

// IncrementGauge mocks base method.
func (m *MockDnsResolverConfigHandle) IncrementGauge(id shared.MetricID, labelValues []string, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementGauge", id, labelValues, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// IncrementGauge indicates an expected call of IncrementGauge.
func (mr *MockDnsResolverConfigHandleMockRecorder) IncrementGauge(id, labelValues, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementGauge", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).IncrementGauge), id, labelValues, value)
}

// RecordHistogramValue mocks base method.
func (m *MockDnsResolverConfigHandle) RecordHistogramValue(id shared.MetricID, labelValues []string, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHistogramValue", id, labelValues, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// RecordHistogramValue indicates an expected call of RecordHistogramValue.
func (mr *MockDnsResolverConfigHandleMockRecorder) RecordHistogramValue(id, labelValues, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHistogramValue", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).RecordHistogramValue), id, labelValues, value)
}

// ResolveComplete mocks base method.
func (m *MockDnsResolverConfigHandle) ResolveComplete(queryID uint64, status shared.DnsResolutionStatus, details string, addresses []shared.DnsAddress) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResolveComplete", queryID, status, details, addresses)
}

// ResolveComplete indicates an expected call of ResolveComplete.
func (mr *MockDnsResolverConfigHandleMockRecorder) ResolveComplete(queryID, status, details, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveComplete", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).ResolveComplete), queryID, status, details, addresses)
}

// SetGauge mocks base method.
func (m *MockDnsResolverConfigHandle) SetGauge(id shared.MetricID, labelValues []string, value uint64) shared.MetricsResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", id, labelValues, value)
	ret0, _ := ret[0].(shared.MetricsResult)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockDnsResolverConfigHandleMockRecorder) SetGauge(id, labelValues, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockDnsResolverConfigHandle)(nil).SetGauge), id, labelValues, value)
}
