use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
  // This is Envoy CI specific: Check if "/opt/llvm/bin/clang" exists, and if it does, set the
  // CLANG_PATH environment variable. CLANG_PATH is for clang-sys used by bindgen:
  // https://github.com/KyleMayes/clang-sys?tab=readme-ov-file#environment-variables
  //
  // "/opt/llvm/bin/clang" exists in Envoy CI containers. If the clang doesn't exist there, bindgen
  // will try to use the system clang from PATH. So, this doesn't affect the local builds.
  // In any case, clang must be found to build the bindings.

  println!("cargo:rerun-if-changed=../../abi/abi.h");

  let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
  let abi_version_path = out_path.join("generated_abi_version.h");

  // Calculate SHA256 of abi.h to generate abi_version.h
  let output = Command::new("sha256sum")
    .arg("../../abi/abi.h")
    .output()
    .or_else(|_| {
      Command::new("shasum")
        .arg("-a")
        .arg("256")
        .arg("../../abi/abi.h")
        .output()
    })
    .expect("Failed to execute sha256sum or shasum. Make sure one of them is available in PATH.");

  if !output.status.success() {
    panic!(
      "Failed to calculate hash: {}",
      String::from_utf8_lossy(&output.stderr)
    );
  }

  let hash = String::from_utf8(output.stdout)
    .expect("Invalid UTF-8 output")
    .split_whitespace()
    .next()
    .expect("No hash output")
    .to_string();

  let version_content = format!(
    r#"#pragma once
#ifdef __cplusplus
namespace Envoy {{
namespace Extensions {{
namespace DynamicModules {{
#endif
// This file is auto-generated by build.rs
const char* kAbiVersion = "{}";
#ifdef __cplusplus
}} // namespace DynamicModules
}} // namespace Extensions
}} // namespace Envoy
#endif
"#,
    hash
  );

  std::fs::write(&abi_version_path, version_content).expect("Failed to write generated header");

  let bindings = bindgen::Builder::default()
    .header("../../abi/abi.h")
    .header(abi_version_path.to_str().unwrap())
    .clang_arg("-v")
    .default_enum_style(bindgen::EnumVariation::Rust {
      non_exhaustive: false,
    })
    .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
    .parse_callbacks(Box::new(TrimEnumNameFromVariantName))
    .generate()
    .expect("Unable to generate bindings");

  bindings
    .write_to_file(out_path.join("bindings.rs"))
    .expect("Couldn't write bindings");
}

#[derive(Debug)]
// This allows us to simplify the enum variant names.
// Otherwise, the generated enum result would be `EnumName::EnumName_VariantName`. E.g.
// `envoy_dynamic_module_type_on_http_filter_response_trailers_status::envoy_dynamic_module_type_on_http_filter_response_trailers_status_Continue`
// instead of `envoy_dynamic_module_type_on_http_filter_response_trailers_status::Continue`.
//
// See https://github.com/rust-lang/rust-bindgen/issues/777
struct TrimEnumNameFromVariantName;

impl bindgen::callbacks::ParseCallbacks for TrimEnumNameFromVariantName {
  fn enum_variant_name(
    &self,
    enum_name: Option<&str>,
    original_variant_name: &str,
    _variant_value: bindgen::callbacks::EnumVariantValue,
  ) -> Option<String> {
    let variant_name = match enum_name {
      Some(enum_name) => original_variant_name
        .trim_start_matches(enum_name.trim_start_matches("enum "))
        .trim_start_matches('_'),
      None => original_variant_name,
    };
    Some(variant_name.to_string())
  }
}
