#!/bin/bash

set -euo pipefail

readonly bazel_version="0.28.0"
if [[ $OSTYPE == darwin* ]]; then
  readonly bazel_platform="darwin"
  readonly bazel_version_sha="572a34b3aac1e891d6bc6d7b0c58ffcbd86eac52f8bcc02f069a8be5af44bf5e"
else
  readonly bazel_platform="linux"
  readonly bazel_version_sha="6564a9ccb2ab4e39696f20254f3c1a900992e849d1307d8abed708bf48acc4ee"
fi

readonly bazel_version_url="https://github.com/bazelbuild/bazel/releases/download/$bazel_version/bazel-$bazel_version-$bazel_platform-x86_64"
readonly script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly bazel_root="$script_root/tmp/bazel/versions/$bazel_version-$bazel_platform"
readonly bazel_executable="$bazel_root/bin/bazel"

if [[ ! -x "$bazel_executable" ]]; then
  echo "Installing bazel..." >&2
  mkdir -p "$(dirname "$bazel_executable")"
  extra_curl_args=""
  if [[ -n "${BUILD_BUILDID:-}" ]]; then
    extra_curl_args="--silent"
  fi

  curl \
    --show-error \
    $extra_curl_args \
    --progress-bar \
    --retry 3 \
    --fail \
    --location \
    --output "$bazel_executable" \
    "$bazel_version_url"

  if echo "$bazel_version_sha  $bazel_executable" | shasum --check --status; then
    chmod +x "$bazel_executable"
  else
    echo "Bazel installer sha mismatch" >&2
    rm -f "$bazel_executable"
    exit 1
  fi
fi

exec "$bazel_executable" "$@"
