version_info: '1'
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.FilterChain
  name: default
  filters:
  - name: envoy.filters.network.http_connection_manager
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: ingress2
      rds:
        route_config_name: dynamic_route_table
        config_source:
          path_config_source:
            path: /usr/local/google/home/kuat/Documents/envoy/configs/fcds/rds.yaml
            watched_directory:
              path: /usr/local/google/home/kuat/Documents/envoy/configs/fcds

      #route_config:
      #  name: ingress
      #  virtual_hosts:
      #    - name: backend
      #      domains:
      #        - "*"
      #      routes:
      #        - match:
      #            prefix: "/"
      #          direct_response:
      #            status: "200"
      #            body:
      #              inline_string: "Hello World!!!\n"
      http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
