#!/bin/bash -e

echo "$@"

VERIFY_COMMAND="$1"
TESTFILE="$2"
VERSION="$3"
CONFIG="$4"

shift 4

echo "VERIFY_COMMAND: ${VERIFY_COMMAND}"
echo "TESTFILE: ${TESTFILE}"
echo "VERSION: ${VERSION}"
echo "CONFIG: ${CONFIG}"

"$VERIFY_COMMAND" "$TESTFILE" "$VERSION" "$CONFIG" "${@}"
