version_info: '1'
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: loopback
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000
  listener_filters:
  filter_chains:
    filters:
    - name: loopback
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        stat_prefix: loopback
        cluster: loopback
