#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXPIRED_CERT_256_HASH[] =
    "67d60f9de9d84e05017bef62812e7780fd3835d60c8de2aa9261d545f1227269";
constexpr char TEST_EXPIRED_CERT_1_HASH[] = "1fe8bba74d875d9c1fb53ab62395e059666ce6b1";
constexpr char TEST_EXPIRED_CERT_SPKI[] = "CsgIWt59ad82D35Pit2zUefNc9g3HKkqwQFKQoRJxpc=";
constexpr char TEST_EXPIRED_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c358";
constexpr char TEST_EXPIRED_CERT_NOT_BEFORE[] = "Aug 20 12:26:26 2026 GMT";
constexpr char TEST_EXPIRED_CERT_NOT_AFTER[] = "Aug 21 12:26:26 2026 GMT";
