#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXPIRED_CERT_256_HASH[] =
    "beabc1fed8aad0316f782aa55e3d7ff49a28ff176eafa065663bd8149be98644";
constexpr char TEST_EXPIRED_CERT_1_HASH[] = "0d70d858e7dfed0442b6c37c27c419819da69382";
constexpr char TEST_EXPIRED_CERT_SPKI[] = "Lcbg5EwN+JNIPGuPpZPoBunTn2T3QQVWkcfyZqHFXVY=";
constexpr char TEST_EXPIRED_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd214";
constexpr char TEST_EXPIRED_CERT_NOT_BEFORE[] = "Oct 23 20:45:48 2024 GMT";
constexpr char TEST_EXPIRED_CERT_NOT_AFTER[] = "Oct 22 20:45:48 2024 GMT";
