// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXTENSIONS_CERT_256_HASH[] =
    "7dc867faf68217497f1a6ae2ccbc9e76bf4655495f9e2887519731e7c3f22be2";
constexpr char TEST_EXTENSIONS_CERT_1_HASH[] = "1aa902994a0471c1d6d7d60ef65b9614ff22aacb";
constexpr char TEST_EXTENSIONS_CERT_SPKI[] = "isXehWDFjhJvHVEhvsyxhiC2oIIZUr48O3yVdI0dYSs=";
constexpr char TEST_EXTENSIONS_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d93e";
constexpr char TEST_EXTENSIONS_CERT_NOT_BEFORE[] = "Oct 16 19:38:40 2024 GMT";
constexpr char TEST_EXTENSIONS_CERT_NOT_AFTER[] = "Oct 16 19:38:40 2026 GMT";
