#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_EXTENSIONS_CERT_256_HASH[] =
    "fe58dd44906bb7120a5319779e2f400ac960d3e0145e6f5aa81957dc0926b736";
constexpr char TEST_EXTENSIONS_CERT_1_HASH[] = "bc08ff837e0f223fb66deee345699e2477c6eb51";
constexpr char TEST_EXTENSIONS_CERT_SPKI[] = "Qz81iBnO1gczPxNIJilqTXKJdcGw1F23uVwSsdNFjco=";
constexpr char TEST_EXTENSIONS_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a661";
constexpr char TEST_EXTENSIONS_CERT_NOT_BEFORE[] = "Aug 22 04:53:02 2026 GMT";
constexpr char TEST_EXTENSIONS_CERT_NOT_AFTER[] = "Aug 21 04:53:02 2028 GMT";
