#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_FAKE_CA_CERT_256_HASH[] =
    "42d9e3dc8595f32d883cf06c1b83231485bc42efe98bc2403e8e16f8a9fe3f57";
constexpr char TEST_FAKE_CA_CERT_1_HASH[] = "0bbb8550e02bff331c4c3bb6ec1c33be37446e32";
constexpr char TEST_FAKE_CA_CERT_SPKI[] = "72Zzz56nYpe0ipkMDMFSnI3wuH7mrIYYB/6+3wb5koM=";
constexpr char TEST_FAKE_CA_CERT_SERIAL[] = "039ff4e1994c31e003c567903f7edfb7912eef5b";
constexpr char TEST_FAKE_CA_CERT_NOT_BEFORE[] = "Aug 22 04:52:58 2026 GMT";
constexpr char TEST_FAKE_CA_CERT_NOT_AFTER[] = "Aug 21 04:52:58 2028 GMT";
