#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_FAKE_CA_CERT_256_HASH[] =
    "50520a06634ec23141a4e025728368502dd22f58aa70892550014e2ff51955d2";
constexpr char TEST_FAKE_CA_CERT_1_HASH[] = "b32d3cb71fc61e055fabdf65aa102da0e3abb79a";
constexpr char TEST_FAKE_CA_CERT_SPKI[] = "P8G7tUGhkgAWSXg51lSt7U8w6DntB6bDWWriKT+FVag=";
constexpr char TEST_FAKE_CA_CERT_SERIAL[] = "21d08524d94c49d918d4a1383b4e98480d9fe085";
constexpr char TEST_FAKE_CA_CERT_NOT_BEFORE[] = "Aug 22 12:26:23 2026 GMT";
constexpr char TEST_FAKE_CA_CERT_NOT_AFTER[] = "Aug 21 12:26:23 2028 GMT";
