#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_256_HASH[] =
    "2dfc0deabdab2009219bba41f9068fe7a56b6ff7872aef8c89727fb3c347e3ce";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_1_HASH[] = "5fc27bc3942282809813fb52f7610ddf1cf06e1a";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_SPKI[] = "4kQ7UToRRkpv38Gz34GFFY5HMtTcmNG8fPgoMxREcSU=";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a668";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_NOT_BEFORE[] = "Aug 22 04:53:05 2026 GMT";
constexpr char TEST_KEYUSAGE_CRL_SIGN_CERT_NOT_AFTER[] = "Aug 21 04:53:05 2028 GMT";
