// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_LONG_VALIDITY_CERT_256_HASH[] =
    "5e19973733c21996d191db00d1452118ad22e459fba7d83af7ec8464d14e86d6";
constexpr char TEST_LONG_VALIDITY_CERT_1_HASH[] = "449e3ccc497d4cae3c74bfd5326c825a6a5ac664";
constexpr char TEST_LONG_VALIDITY_CERT_SPKI[] = "jZqH7xNa2sefhllzMvr8wkbb0OtH6sHof6YftyJRTWc=";
constexpr char TEST_LONG_VALIDITY_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d940";
constexpr char TEST_LONG_VALIDITY_CERT_NOT_BEFORE[] = "Oct 16 19:38:42 2024 GMT";
constexpr char TEST_LONG_VALIDITY_CERT_NOT_AFTER[] = "Oct  4 19:38:42 2074 GMT";
