// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_EXTENSION_CERT_256_HASH[] =
    "65ecb451bc7f5bf53d5c93553fab91c9c76dce69f92eda4bbd43f737789703e1";
constexpr char TEST_NO_EXTENSION_CERT_1_HASH[] = "baf9699217e4f8315b9bd3467b526b9f3d64c18c";
constexpr char TEST_NO_EXTENSION_CERT_SPKI[] = "jTur4hpf6n/0OfaTXIVX1X65Z78HOrSGF6T3AzZXsOw=";
constexpr char TEST_NO_EXTENSION_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d944";
constexpr char TEST_NO_EXTENSION_CERT_NOT_BEFORE[] = "Oct 16 19:38:43 2024 GMT";
constexpr char TEST_NO_EXTENSION_CERT_NOT_AFTER[] = "Oct 16 19:38:43 2026 GMT";
