// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_SUBJECT_CERT_256_HASH[] =
    "2684a5baec93d5af5935804d75b17c773a6f63f99241a2c2b0c0fc49365d473f";
constexpr char TEST_NO_SUBJECT_CERT_1_HASH[] = "293dd9a6e166cce26c5f2885d394128804a73ebd";
constexpr char TEST_NO_SUBJECT_CERT_SPKI[] = "EwsEqThR/HIk3zXHxILE/DEySY97Jnu96HIOuS4E9b0=";
constexpr char TEST_NO_SUBJECT_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d943";
constexpr char TEST_NO_SUBJECT_CERT_NOT_BEFORE[] = "Oct 16 19:38:42 2024 GMT";
constexpr char TEST_NO_SUBJECT_CERT_NOT_AFTER[] = "Oct 16 19:38:42 2026 GMT";
