#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_SAN_CN_CERT_256_HASH[] =
    "e21ca6d8f07916b0355b4148da67ced09040a1e140a2c67a86ed72d9d946bf89";
constexpr char TEST_NO_SAN_CN_CERT_1_HASH[] = "b2f36cc41eaa6ba7c07243aa35936e2586a1fe4b";
constexpr char TEST_NO_SAN_CN_CERT_SPKI[] = "QqBogLg4Cgd4pLqp8858l/S3B3VPgA7ZTmAqp3bsm/4=";
constexpr char TEST_NO_SAN_CN_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd200";
constexpr char TEST_NO_SAN_CN_CERT_NOT_BEFORE[] = "Oct 23 20:45:41 2024 GMT";
constexpr char TEST_NO_SAN_CN_CERT_NOT_AFTER[] = "Oct 23 20:45:41 2026 GMT";
