#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NO_SUBJECT_CERT_256_HASH[] =
    "2e226b66670a9186ce4382b5bef2791372e7b86994870f4d7e9f16c0261edc7c";
constexpr char TEST_NO_SUBJECT_CERT_1_HASH[] = "9ad6c62f835054f7e7c45412d6826951f977da61";
constexpr char TEST_NO_SUBJECT_CERT_SPKI[] = "lvgpdVvTKVuzWaGYL5xtON7pybWmH0+6goEhFqgEs+4=";
constexpr char TEST_NO_SUBJECT_CERT_SERIAL[] = "3ab370888bba18071dd1beaf74e78c613e49057a";
constexpr char TEST_NO_SUBJECT_CERT_NOT_BEFORE[] = "Aug 21 19:14:11 2024 GMT";
constexpr char TEST_NO_SUBJECT_CERT_NOT_AFTER[] = "Aug 21 19:14:11 2026 GMT";
