#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_NON_SPIFFE_SAN_CERT_256_HASH[] =
    "8d03c9578e02b7b327916ea2402d445a8c90aad34b27e063c8d9e950aeccbaec";
constexpr char TEST_NON_SPIFFE_SAN_CERT_1_HASH[] = "28badbe4f7b025218905c4b2a83a53047b235db7";
constexpr char TEST_NON_SPIFFE_SAN_CERT_SPKI[] = "gGNIOJFYVbu8joTbbdxocRv/oTnXf8vA+XWdjJPfRtg=";
constexpr char TEST_NON_SPIFFE_SAN_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd21b";
constexpr char TEST_NON_SPIFFE_SAN_CERT_NOT_BEFORE[] = "Oct 23 20:45:49 2024 GMT";
constexpr char TEST_NON_SPIFFE_SAN_CERT_NOT_AFTER[] = "Oct 23 20:45:49 2026 GMT";
