#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_PASSWORD_PROTECTED_CERT_256_HASH[] =
    "9820dad8da896d77b2aa15521ef0d93f93eac6a3c7b060aef0a10f39ce970855";
constexpr char TEST_PASSWORD_PROTECTED_CERT_1_HASH[] = "1f6086f910f50e13dbd9c9345d8dc240cc27a8d3";
constexpr char TEST_PASSWORD_PROTECTED_CERT_SPKI[] = "jGQ8b0nFa/KlDj9zAvByUOBdKkRAZC/fiu/9mo8gIoc=";
constexpr char TEST_PASSWORD_PROTECTED_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c356";
constexpr char TEST_PASSWORD_PROTECTED_CERT_NOT_BEFORE[] = "Aug 22 12:26:25 2026 GMT";
constexpr char TEST_PASSWORD_PROTECTED_CERT_NOT_AFTER[] = "Aug 21 12:26:25 2028 GMT";
