// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_PASSWORD_PROTECTED_CERT_256_HASH[] =
    "fc16cae676dae072d27daa97eba9f4b45fed07bb1751f9bc14b4eb13a64b547a";
constexpr char TEST_PASSWORD_PROTECTED_CERT_1_HASH[] = "a972e79fc83c50164817feaa28ac5328e07ab345";
constexpr char TEST_PASSWORD_PROTECTED_CERT_SPKI[] = "UpMtjpn9yJcyofq3GPhlTxY5QrSzLPUeXdOCH6bEUzw=";
constexpr char TEST_PASSWORD_PROTECTED_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d93f";
constexpr char TEST_PASSWORD_PROTECTED_CERT_NOT_BEFORE[] = "Oct 16 19:38:40 2024 GMT";
constexpr char TEST_PASSWORD_PROTECTED_CERT_NOT_AFTER[] = "Oct 16 19:38:40 2026 GMT";
