#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_PASSWORD_PROTECTED_CERT_256_HASH[] =
    "02ae6dd1db79ac0a020a5afbe24e4b178b5fbc3a39f362ef163945005b0d1c64";
constexpr char TEST_PASSWORD_PROTECTED_CERT_1_HASH[] = "e8c1a6f440aca7411c6a5f4716c6ead1f4537f12";
constexpr char TEST_PASSWORD_PROTECTED_CERT_SPKI[] = "eCBMcBeVaEhfu1ojNJCD+qT9QdyRNvBpNuwSmPf2eKk=";
constexpr char TEST_PASSWORD_PROTECTED_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a662";
constexpr char TEST_PASSWORD_PROTECTED_CERT_NOT_BEFORE[] = "Aug 22 04:53:02 2026 GMT";
constexpr char TEST_PASSWORD_PROTECTED_CERT_NOT_AFTER[] = "Aug 21 04:53:02 2028 GMT";
