#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_256_HASH[] =
    "7d03947fff96319030f737bd9e0016558de50cf167c3922f6af8aae5b6731169";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_1_HASH[] =
    "40db68e3336bbaf943021b6778cb70b2cf67d716";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_SPKI[] =
    "9RzgmDk2njqgW8vYOK8jx4T7yAbBhnJ+3V3XT/zWxlA=";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_SERIAL[] =
    "3ab370888bba18071dd1beaf74e78c613e490574";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_NOT_BEFORE[] = "Aug 21 19:14:08 2024 GMT";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_NOT_AFTER[] = "Aug 21 19:14:08 2026 GMT";
