#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_CERT_256_HASH[] =
    "d3ed76ddc6b9796345ac297570998c5d1a9d276bdf908e8c96e6f4db20161621";
constexpr char TEST_SAN_DNS_CERT_1_HASH[] = "254586ed7b011d5c5753f8c09ade7276a71005b9";
constexpr char TEST_SAN_DNS_CERT_SPKI[] = "QF8K9D70mYZalicMnzbSAlNBJIcfWx+i3pRnDfuqamw=";
constexpr char TEST_SAN_DNS_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c343";
constexpr char TEST_SAN_DNS_CERT_NOT_BEFORE[] = "Aug 22 12:26:23 2026 GMT";
constexpr char TEST_SAN_DNS_CERT_NOT_AFTER[] = "Aug 21 12:26:23 2028 GMT";
