#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_256_HASH[] =
    "6c7f15d403c89821e0cded87e35db7c684fdbf02766e0dcf2f56e535c03659d1";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_1_HASH[] =
    "2f546163dc189fa0a7dffb915b074b8ad1fdd44c";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_SPKI[] =
    "42Rr8dbbT7qqARonAHVvV+ZXdIElKvEeHSSV95FBh14=";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_SERIAL[] =
    "3ab370888bba18071dd1beaf74e78c613e490572";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_NOT_BEFORE[] = "Aug 21 19:14:07 2024 GMT";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_NOT_AFTER[] = "Aug 21 19:14:07 2026 GMT";
