#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_WILDCARD_DNS_CERT_256_HASH[] =
    "d45feecc3df046721a99ed5862eeb67c2536605881a79b268dc0567a5a0ed410";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_1_HASH[] = "3b201332a3f8d373175bbac8559e1d8bca4cb0be";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_SPKI[] = "iwHKgYKs4gHIIqxxibb2QrOY99JcYqVgzG48biH6Y68=";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_SERIAL[] = "3ab370888bba18071dd1beaf74e78c613e490567";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_NOT_BEFORE[] = "Aug 21 19:14:05 2024 GMT";
constexpr char TEST_SAN_WILDCARD_DNS_CERT_NOT_AFTER[] = "Aug 21 19:14:05 2026 GMT";
