#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_256_HASH[] =
    "96438dc538665c260e60afe36381ef57568030576426ecd5751fbfa7adc11075";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_1_HASH[] = "0db3256f5a1d054343ffe4b1a2d90b4a32682563";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_SPKI[] = "ueCIAlVzSs9BaSyRr4ltbz+sKd/ioFXbL8b+2/0aGG8=";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c348";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_NOT_BEFORE[] = "Aug 22 12:26:24 2026 GMT";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_NOT_AFTER[] = "Aug 21 12:26:24 2028 GMT";
