#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS4_CERT_256_HASH[] =
    "feabf33cb88a97b5a6e52fc06fe6780e2bd546b156188c1a887cb060574961d5";
constexpr char TEST_SAN_DNS4_CERT_1_HASH[] = "ad0e91fb1fc7323a641f6264175105092baace0c";
constexpr char TEST_SAN_DNS4_CERT_SPKI[] = "WkJIDnbxTlpEMMI+NWC4BmacfDGTtT9U9FDMaTw16Wo=";
constexpr char TEST_SAN_DNS4_CERT_SERIAL[] = "3a3085513d93701fc3a345070a6fed9fcf6259a7";
constexpr char TEST_SAN_DNS4_CERT_NOT_BEFORE[] = "Oct 23 20:45:42 2024 GMT";
constexpr char TEST_SAN_DNS4_CERT_NOT_AFTER[] = "Oct 23 20:45:42 2026 GMT";
