// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_2_CERT_256_HASH[] =
    "d4d56e8af3a3453866d82e777396c5c117b2fca96958e69101403fe9c75f7f2a";
constexpr char TEST_SAN_DNS_RSA_2_CERT_1_HASH[] = "2067ecb4ae3c7ffebb6481e0b7e7e59037fdcaff";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SPKI[] = "k1gy/SyBLKvp1Zslud7vL2q85mN/P4UTb+jJ7QiBcRo=";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d935";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_BEFORE[] = "Oct 16 19:38:38 2024 GMT";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_AFTER[] = "Oct 16 19:38:38 2026 GMT";
