// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_CERT_256_HASH[] =
    "72d81e3fce7e2ead1417a0a7493e726a9c19cde09e391dd06c78dd46111e14dc";
constexpr char TEST_SAN_DNS_CERT_1_HASH[] = "dece24656bba26c70e71558a5a44a3815d59be27";
constexpr char TEST_SAN_DNS_CERT_SPKI[] = "KD0YalR8L3AZuQynJgNTjwVKG4MvXMfiIBPUypHzcEw=";
constexpr char TEST_SAN_DNS_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d92e";
constexpr char TEST_SAN_DNS_CERT_NOT_BEFORE[] = "Oct 16 19:38:36 2024 GMT";
constexpr char TEST_SAN_DNS_CERT_NOT_AFTER[] = "Oct 16 19:38:36 2026 GMT";
