#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_ONLY_DNS_CERT_256_HASH[] =
    "cea415682b6bb248e58e3c6f20dbcf18de47fe3c361febd04ab610bb72e72d88";
constexpr char TEST_SAN_ONLY_DNS_CERT_1_HASH[] = "8a99aa2012184805793cd98046824bc418f37844";
constexpr char TEST_SAN_ONLY_DNS_CERT_SPKI[] = "r69sLXeyoKvw2YUnEY78HqpOlL52V52QQZEL7H+NEHI=";
constexpr char TEST_SAN_ONLY_DNS_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd206";
constexpr char TEST_SAN_ONLY_DNS_CERT_NOT_BEFORE[] = "Oct 23 20:45:43 2024 GMT";
constexpr char TEST_SAN_ONLY_DNS_CERT_NOT_AFTER[] = "Oct 23 20:45:43 2026 GMT";
