// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_256_HASH[] =
    "ad6795de9165807ee6f638554113dd4c451485785255e0c3bfd4b7e62c9b2b3c";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_1_HASH[] = "ad65af2874aeb4b5fd63e1d112e3035e319d03a7";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_SPKI[] = "eGuPaXuk9DwLl63Pidd4nEyMUNm2F+bss9PTS4MmbY0=";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d932";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_NOT_BEFORE[] = "Oct 16 19:38:37 2024 GMT";
constexpr char TEST_SAN_MULTIPLE_DNS_1_CERT_NOT_AFTER[] = "Oct 16 19:38:37 2026 GMT";
