#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_OTHERNAME_CERT_256_HASH[] =
    "b9f4c275c4aa519348e1e5fac15aa03aad4a65f85992f1f51f74788dcc14ebef";
constexpr char TEST_SAN_OTHERNAME_CERT_1_HASH[] = "cbae4f06a5486cb33635d1738d4ab94da55f3eca";
constexpr char TEST_SAN_OTHERNAME_CERT_SPKI[] = "iM38krp50hJf1j/LFCJ5Jtn5eQEPbQVXCNIMuNo6FO8=";
constexpr char TEST_SAN_OTHERNAME_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a65d";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_BEFORE[] = "Aug 22 04:53:01 2026 GMT";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_AFTER[] = "Aug 21 04:53:01 2028 GMT";
