#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_OTHERNAME_CERT_256_HASH[] =
    "78a158bbd21e798ec25ddc200a5802c440dc4121fb3ed2bc87eef1c36913c597";
constexpr char TEST_SAN_OTHERNAME_CERT_1_HASH[] = "ac15c570fc9d49b17f6f21d9bd5ff31fc97ca857";
constexpr char TEST_SAN_OTHERNAME_CERT_SPKI[] = "PAzhw9z9+nSiy1XHqvlppqXpSbOl+Wv+YnEeeEbdsrY=";
constexpr char TEST_SAN_OTHERNAME_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c351";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_BEFORE[] = "Aug 22 12:26:24 2026 GMT";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_AFTER[] = "Aug 21 12:26:24 2028 GMT";
