// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_256_HASH[] =
    "dae0bfd8259d36201ba4747a80b87abf851df0714b66483b98d62484685c69cb";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_1_HASH[] = "a30bc69c5f620f031decce172051ae1fad2ddc95";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_SPKI[] = "K7zxsDifFvPP7qQUnA/tSV7LA8nQSMNzlyfW5Mq3klk=";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d936";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_NOT_BEFORE[] = "Oct 16 19:38:38 2024 GMT";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_NOT_AFTER[] = "Oct 16 19:38:38 2026 GMT";
