#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_URI_CERT_256_HASH[] =
    "d4b6682feec926380cb10cb61499daa1e674127778560c71b5a898f803651140";
constexpr char TEST_SAN_URI_CERT_1_HASH[] = "e9da20502a81c928a39b1e300c9b3a0176471fe0";
constexpr char TEST_SAN_URI_CERT_SPKI[] = "E2sqZaH9XqHIEfvjwBysCAecpyDfLXe1yHOvfynExGY=";
constexpr char TEST_SAN_URI_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a65b";
constexpr char TEST_SAN_URI_CERT_NOT_BEFORE[] = "Aug 22 04:53:00 2026 GMT";
constexpr char TEST_SAN_URI_CERT_NOT_AFTER[] = "Aug 21 04:53:00 2028 GMT";
