// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS3_CERT_256_HASH[] =
    "420dad00eb4e0dd7b4338e13af0571d8934ece531fc0dd29ae8d783b624fd025";
constexpr char TEST_SAN_DNS3_CERT_1_HASH[] = "bfbd0644a4c6faaca2de63ec60762a353766c63d";
constexpr char TEST_SAN_DNS3_CERT_SPKI[] = "pb3Ie4cKh2AJ8VHEAoKfqfABZACh3VBXZV0GLbIw3YA=";
constexpr char TEST_SAN_DNS3_CERT_SERIAL[] = "3d71fe2b65ac503cde3c6a7e8398298834b2bfec";
constexpr char TEST_SAN_DNS3_CERT_NOT_BEFORE[] = "Oct 16 19:38:36 2024 GMT";
constexpr char TEST_SAN_DNS3_CERT_NOT_AFTER[] = "Oct 16 19:38:36 2026 GMT";
