// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_IP_CERT_256_HASH[] =
    "d5790e229b5326b6272c3184e09b0b3c58bd8a99f92f6277d73782e9448479a7";
constexpr char TEST_SAN_IP_CERT_1_HASH[] = "67e195a842b8bd0ade3f2402f545d00ccee84588";
constexpr char TEST_SAN_IP_CERT_SPKI[] = "zBN2ET/YZPqIJ8SrBqCVlIq9DS5IwTfQ7/dQv5wX/Hk=";
constexpr char TEST_SAN_IP_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d939";
constexpr char TEST_SAN_IP_CERT_NOT_BEFORE[] = "Oct 16 19:38:39 2024 GMT";
constexpr char TEST_SAN_IP_CERT_NOT_AFTER[] = "Oct 16 19:38:39 2026 GMT";
