#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_2_CERT_256_HASH[] =
    "6a6956a32abb43b3424bdd9298fe9e86a1421f2f3a00f0f76fd1c8974bdf0ee1";
constexpr char TEST_SAN_DNS_RSA_2_CERT_1_HASH[] = "0b6af6a7041be3c3e4fa3a34dea3b24908e0a581";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SPKI[] = "DnAZMBAZx67mU5TcKkzY19w42nw/v/TqeKQpPBBYRoM=";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SERIAL[] = "3ab370888bba18071dd1beaf74e78c613e49056c";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_BEFORE[] = "Aug 21 19:14:06 2024 GMT";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_AFTER[] = "Aug 21 19:14:06 2026 GMT";
