#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_256_HASH[] =
    "b9aee8fdc124c25c190b22c68719a6c842dcfe782308fc80f30749d59fee12e1";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_1_HASH[] = "4642de93b2cbe9e9073ba7fbc0dd683e04ea165f";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_SPKI[] = "hvD6UxuKnnrNzTOR7kmAuvIhZtRrsB3mYwE+leuN0rA=";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c34e";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_NOT_BEFORE[] = "Aug 22 12:26:24 2026 GMT";
constexpr char TEST_SAN_DNS_ECDSA_2_CERT_NOT_AFTER[] = "Aug 21 12:26:24 2028 GMT";
