#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_2_CERT_256_HASH[] =
    "8e73f3034cd8084ccffc0f938492687e8fa14411da49d89c36430e31731db99a";
constexpr char TEST_SAN_DNS_RSA_2_CERT_1_HASH[] = "772eb0371224620c1ba09f3fadd8d402af75e06a";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SPKI[] = "vFxCWvHOf3nd+0lIp51F+5s5Gz8/BjoGLBmtkSGCpFU=";
constexpr char TEST_SAN_DNS_RSA_2_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd208";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_BEFORE[] = "Oct 23 20:45:43 2024 GMT";
constexpr char TEST_SAN_DNS_RSA_2_CERT_NOT_AFTER[] = "Oct 23 20:45:43 2026 GMT";
