// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_OTHERNAME_CERT_256_HASH[] =
    "b14fc98da942922bcf1f38e02b1ac811ce0707ce0ebc6fcaaf2c9ab23989f071";
constexpr char TEST_SAN_OTHERNAME_CERT_1_HASH[] = "7a90a44fb7e9277a384489dc58f0038c59bfddd4";
constexpr char TEST_SAN_OTHERNAME_CERT_SPKI[] = "O4c/0Yqaskqd7L5oqV6NhqHnFsNKIF0NJce65qROvvk=";
constexpr char TEST_SAN_OTHERNAME_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d93a";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_BEFORE[] = "Oct 16 19:38:39 2024 GMT";
constexpr char TEST_SAN_OTHERNAME_CERT_NOT_AFTER[] = "Oct 16 19:38:39 2026 GMT";
