#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_256_HASH[] =
    "281a868bcbd580df99bd8caa6bac3c91fd416a00b27a6baa5d24c96a9f1d357d";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_1_HASH[] = "ba9371fe49b828aee8ab0c309d376caa5a4d25d7";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_SPKI[] = "eZxLzWTtshkLG0mxBvNf6OLEW/eYJhN6x3Xk5sui/rw=";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c352";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_NOT_BEFORE[] = "Aug 22 12:26:24 2026 GMT";
constexpr char TEST_SAN_MULTIPLE_OTHERNAME_CERT_NOT_AFTER[] = "Aug 21 12:26:24 2028 GMT";
