#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_CERT_256_HASH[] =
    "bf86479f8c30e05380e5770cef7b14a797e9f9c71ff44d95aa41ef71e5696cb2";
constexpr char TEST_SAN_DNS_CERT_1_HASH[] = "f76129f16a2f565fbb90683c7a15ac8ce6df1b0b";
constexpr char TEST_SAN_DNS_CERT_SPKI[] = "w3H5YKi+aQ+XQwvCm0xsJut9ctZOeRPsQ+HD6r0I04I=";
constexpr char TEST_SAN_DNS_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a64f";
constexpr char TEST_SAN_DNS_CERT_NOT_BEFORE[] = "Aug 22 04:52:58 2026 GMT";
constexpr char TEST_SAN_DNS_CERT_NOT_AFTER[] = "Aug 21 04:52:58 2028 GMT";
