#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_256_HASH[] =
    "03d1114c40c8bc314d47ba969d2d70f6c75c6857776338f0325237b5411d895a";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_1_HASH[] = "5b1eb3148c3ae7b5fe793d5b4a5b050d22ea07c0";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_SPKI[] = "YHnLfosYcrzmZrwH69DB0euQl6XKaQYKY/HHP/LQrwI=";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c34d";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_NOT_BEFORE[] = "Aug 22 12:26:24 2026 GMT";
constexpr char TEST_SAN_DNS_ECDSA_1_CERT_NOT_AFTER[] = "Aug 21 12:26:24 2028 GMT";
