#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_256_HASH[] =
    "6625a2aebf6cfec3a4af4f2019a43115f6ddae5fff3082e875f285ff7afed7f4";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_1_HASH[] = "5d1c314e9844c932a513f5863680a59b6bf1b7b6";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_SPKI[] = "ITq1MF09AQrwhgqwRSuPOd0xWDm1PT06TLU/2OjEZnU=";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd204";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_NOT_BEFORE[] = "Oct 23 20:45:42 2024 GMT";
constexpr char TEST_SAN_MULTIPLE_DNS_CERT_NOT_AFTER[] = "Oct 23 20:45:42 2026 GMT";
