#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_URI_CERT_256_HASH[] =
    "86d3e4a2cadd6fcd4fb738a41e2d2ea71c0e757bb47b167a57c5e464e12c014b";
constexpr char TEST_SAN_URI_CERT_1_HASH[] = "49d696533bb7215fec3a06d3df43de96f7cfc809";
constexpr char TEST_SAN_URI_CERT_SPKI[] = "N+SbVYu56tsNe8tpVBoyAWeb0Q//pMWNVtYnPlsld4s=";
constexpr char TEST_SAN_URI_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd20b";
constexpr char TEST_SAN_URI_CERT_NOT_BEFORE[] = "Oct 23 20:45:44 2024 GMT";
constexpr char TEST_SAN_URI_CERT_NOT_AFTER[] = "Oct 23 20:45:44 2026 GMT";
