// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_256_HASH[] =
    "71e6c6d39c271ec6664c55a8f258689b32de952fb25dce6adadcc152b55b2ecc";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_1_HASH[] = "e2acfbb287b999925a51b7af42fce0b9cf05ee7a";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_SPKI[] = "dbqxrEZ9frYuUoNvDH59SWf847fg0S9qaNjougLl158=";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_SERIAL[] = "2b8c1ecfaa9c20e88e9f4c7cd900b208ca43d93d";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_NOT_BEFORE[] = "Oct 16 19:38:40 2024 GMT";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_NOT_AFTER[] = "Oct 16 19:38:40 2026 GMT";
