#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS3_CERT_256_HASH[] =
    "4e2371b307d1c0614ba6f1fc20bca7dd5bc205698e9e5d43fad78df14df22cd7";
constexpr char TEST_SAN_DNS3_CERT_1_HASH[] = "6d4f779ccac370f2b0145a1e73529ed441f9844c";
constexpr char TEST_SAN_DNS3_CERT_SPKI[] = "Kgilv9XEgP7VvlWXJnP8BV3+BtdOZCwA/RwihKxGxrw=";
constexpr char TEST_SAN_DNS3_CERT_SERIAL[] = "3a3085513d93701fc3a345070a6fed9fcf6259a6";
constexpr char TEST_SAN_DNS3_CERT_NOT_BEFORE[] = "Oct 23 20:45:42 2024 GMT";
constexpr char TEST_SAN_DNS3_CERT_NOT_AFTER[] = "Oct 23 20:45:42 2026 GMT";
