#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_1_CERT_256_HASH[] =
    "1dbc2c97462f2c8c66c40af69356ce943bec18ff73afbafd52e6f376de33386b";
constexpr char TEST_SAN_DNS_RSA_1_CERT_1_HASH[] = "2f4702c8d262b0352f0413acf51e4feec75a983c";
constexpr char TEST_SAN_DNS_RSA_1_CERT_SPKI[] = "FmzZRJlkHM5Kmejt0teSDNDuu8N0ALQ8VHTi2MU097A=";
constexpr char TEST_SAN_DNS_RSA_1_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a657";
constexpr char TEST_SAN_DNS_RSA_1_CERT_NOT_BEFORE[] = "Aug 22 04:53:00 2026 GMT";
constexpr char TEST_SAN_DNS_RSA_1_CERT_NOT_AFTER[] = "Aug 21 04:53:00 2028 GMT";
