#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_ONLY_DNS_CERT_256_HASH[] =
    "1f00daa602300742542c4cabca0dcef5bf37040638111a96153ac70ec1a833b4";
constexpr char TEST_SAN_ONLY_DNS_CERT_1_HASH[] = "4aa1612a3029a7667e5c04d938532cc0395aa6f8";
constexpr char TEST_SAN_ONLY_DNS_CERT_SPKI[] = "2DAbJleNHjwYSCzh0xQ8DynNG/tJQrkAMgUH2h70CS8=";
constexpr char TEST_SAN_ONLY_DNS_CERT_SERIAL[] = "662bddca794eee2f2c27589f5bc79377aa82a656";
constexpr char TEST_SAN_ONLY_DNS_CERT_NOT_BEFORE[] = "Aug 22 04:53:00 2026 GMT";
constexpr char TEST_SAN_ONLY_DNS_CERT_NOT_AFTER[] = "Aug 21 04:53:00 2028 GMT";
