#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_RSA_1_CERT_256_HASH[] =
    "bb6a6c4b019785e0992ac982e164a4325589b2b4a5f4cd8c9f17d7aa1133e783";
constexpr char TEST_SAN_DNS_RSA_1_CERT_1_HASH[] = "3406b906f0e96193f372d431e8f965ff5fddfc07";
constexpr char TEST_SAN_DNS_RSA_1_CERT_SPKI[] = "yRpbKNMUkyu5DlJfb5PUqlcEeAudDdCXUpAf2HN0Da4=";
constexpr char TEST_SAN_DNS_RSA_1_CERT_SERIAL[] = "69cbbf5ebe25412130395590de05c26935bfd207";
constexpr char TEST_SAN_DNS_RSA_1_CERT_NOT_BEFORE[] = "Oct 23 20:45:43 2024 GMT";
constexpr char TEST_SAN_DNS_RSA_1_CERT_NOT_AFTER[] = "Oct 23 20:45:43 2026 GMT";
