#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_256_HASH[] =
    "bcb8a4e3d6848cfc36a49d24cba52b2336b91f71e6b6d38a21fde4ebd98957a1";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_1_HASH[] =
    "2da2ca174426aa95d5028a62e28318e94d3cdee7";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_SPKI[] =
    "o1n0nHjQE7b2u3hFTbQEVOT7BMuxw2kE2cBjv6L7H/Y=";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_SERIAL[] =
    "69cbbf5ebe25412130395590de05c26935bfd210";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_NOT_BEFORE[] = "Oct 23 20:45:45 2024 GMT";
constexpr char TEST_SAN_DNS_AND_OTHERNAME_CERT_NOT_AFTER[] = "Oct 23 20:45:45 2026 GMT";
