#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_SECP224R1_CERT_256_HASH[] =
    "8ea605ecd1c0e390c3a64a878f02d2a032c7c4f1980ef957f1a8edcd9897f191";
constexpr char TEST_SELFSIGNED_SECP224R1_CERT_1_HASH[] = "e4ffecb3a9fd7894d4cf5d25d048add61b722a1c";
constexpr char TEST_SELFSIGNED_SECP224R1_CERT_SPKI[] =
    "v7FS0bmVCaO3n1TU4vqdleAY6UvYc7nOWC4cUM6bxqk=";
constexpr char TEST_SELFSIGNED_SECP224R1_CERT_SERIAL[] = "2045a88fed871b94b2114e1be4459ba3adcc535d";
constexpr char TEST_SELFSIGNED_SECP224R1_CERT_NOT_BEFORE[] = "Oct 23 20:45:47 2024 GMT";
constexpr char TEST_SELFSIGNED_SECP224R1_CERT_NOT_AFTER[] = "Oct 23 20:45:47 2026 GMT";
