#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_RSA_3072_CERT_256_HASH[] =
    "017eabac25365b653c7e20c0eaf832db156a6acf35deff4273e2e1b4e020a8b3";
constexpr char TEST_SELFSIGNED_RSA_3072_CERT_1_HASH[] = "dd92dfff33a4c84926b4c34d12d4094e69ce7f42";
constexpr char TEST_SELFSIGNED_RSA_3072_CERT_SPKI[] =
    "Bc9Sts9H5XQ3L9X5+J6kM9JLkxCHgMrPB16xAs6P2s4=";
constexpr char TEST_SELFSIGNED_RSA_3072_CERT_SERIAL[] = "0ac9dddee22a1b247fece10277d236f0e10de5c1";
constexpr char TEST_SELFSIGNED_RSA_3072_CERT_NOT_BEFORE[] = "Aug 22 04:53:03 2026 GMT";
constexpr char TEST_SELFSIGNED_RSA_3072_CERT_NOT_AFTER[] = "Aug 21 04:53:03 2028 GMT";
