#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED2_ECDSA_P256_CERT_256_HASH[] =
    "2ac409e5b0eef8a9068b1dbe7c9ff75a673a4a114a98da4da6ea4a43d538bc7f";
constexpr char TEST_SELFSIGNED2_ECDSA_P256_CERT_1_HASH[] =
    "2e759593d702fe4e66b8008ec77d7851d52cd3b6";
constexpr char TEST_SELFSIGNED2_ECDSA_P256_CERT_SPKI[] =
    "BFXLxGfHofz6HUTZWNNY2KgqwGUWdvi/J9HzrWF3zeI=";
constexpr char TEST_SELFSIGNED2_ECDSA_P256_CERT_SERIAL[] =
    "02cab1e63cbd36ea80c44722e5fa038aa7f06161";
constexpr char TEST_SELFSIGNED2_ECDSA_P256_CERT_NOT_BEFORE[] = "Aug 21 19:14:10 2024 GMT";
constexpr char TEST_SELFSIGNED2_ECDSA_P256_CERT_NOT_AFTER[] = "Aug 21 19:14:10 2026 GMT";
