#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_ECDSA_P384_CERT_256_HASH[] =
    "8bad19ca466dd2495389d55513fd31a7a092998ce40886df07d85e17f3e313de";
constexpr char TEST_SELFSIGNED_ECDSA_P384_CERT_1_HASH[] =
    "5046221c84f831d1bbdf0bbca0afe26e2aaee2d3";
constexpr char TEST_SELFSIGNED_ECDSA_P384_CERT_SPKI[] =
    "DrQSrAASmULjhykPL5vcjOOL4+sp2/IJhvYO5MsbBzY=";
constexpr char TEST_SELFSIGNED_ECDSA_P384_CERT_SERIAL[] =
    "5e89a3e2b62c47556d2f052e7361cb74969f1523";
constexpr char TEST_SELFSIGNED_ECDSA_P384_CERT_NOT_BEFORE[] = "Aug 22 04:53:04 2026 GMT";
constexpr char TEST_SELFSIGNED_ECDSA_P384_CERT_NOT_AFTER[] = "Aug 21 04:53:04 2028 GMT";
