#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_256_HASH[] =
    "658f7a30efa6afa92dfd129002bbb6de7906073378e41d54f691a2f8119ff450";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_1_HASH[] = "0a1d67b5e74467a167e4aab6eb54c578a716909f";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_SPKI[] =
    "nlL86j7lXXgRgx9YalOnaR+lL55U2mFpTXyETvMlw6I=";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_SERIAL[] = "66232bb600e7fc7b8aff9f24b747b1dbbaafb94e";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_NOT_BEFORE[] = "Aug 22 04:53:03 2026 GMT";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_NOT_AFTER[] = "Aug 21 04:53:03 2028 GMT";
