// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED2_CERT_256_HASH[] =
    "1ddf9389172cfd0fb80e6a08da45a62bf67f07e04d373d05c79d642afcc4b07e";
constexpr char TEST_SELFSIGNED2_CERT_1_HASH[] = "fd68777613ea35446aa8e6a92bdfde50673a77d1";
constexpr char TEST_SELFSIGNED2_CERT_SPKI[] = "Om/VQJcAR4t4jmEpfkkb06hbUpQHUjEXNY0WeZazlDQ=";
constexpr char TEST_SELFSIGNED2_CERT_SERIAL[] = "7acf7a7f226cc36204cb939ab0fbe1512aa8fb7e";
constexpr char TEST_SELFSIGNED2_CERT_NOT_BEFORE[] = "Oct 16 19:38:40 2024 GMT";
constexpr char TEST_SELFSIGNED2_CERT_NOT_AFTER[] = "Oct 16 19:38:40 2026 GMT";
