#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_CERT_256_HASH[] =
    "7346ffc2016ed3ccfd69e7c9ffcf2ffff041a3c17a8519a3fc046d99c4bf1b78";
constexpr char TEST_SELFSIGNED_CERT_1_HASH[] = "9d4f87087458b71ba0da59423c5a56a8648485b1";
constexpr char TEST_SELFSIGNED_CERT_SPKI[] = "WzRVSPmSTCDNpZt+KV7qaRWVoBSsJ/Qecz4NMXgAHaI=";
constexpr char TEST_SELFSIGNED_CERT_SERIAL[] = "34f8b5cc8a8e0ef668fcb6187c3356eac7900f8a";
constexpr char TEST_SELFSIGNED_CERT_NOT_BEFORE[] = "Aug 21 19:14:08 2024 GMT";
constexpr char TEST_SELFSIGNED_CERT_NOT_AFTER[] = "Aug 21 19:14:08 2026 GMT";
