#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_CERT_256_HASH[] =
    "78154612fc952daa826a82834e6336a6767d4aa25bce90aa4395b3b82143e646";
constexpr char TEST_SELFSIGNED_CERT_1_HASH[] = "fd1b90957dd7354f9674e8e7ad1ab087cb9b6dbd";
constexpr char TEST_SELFSIGNED_CERT_SPKI[] = "voHGlzpF0yb6h/d0V98OPYZ8JUvJppLL4eyHpVyon18=";
constexpr char TEST_SELFSIGNED_CERT_SERIAL[] = "64f257c7eca04a384a4ec937ab44e21ded2ee223";
constexpr char TEST_SELFSIGNED_CERT_NOT_BEFORE[] = "Aug 22 12:26:25 2026 GMT";
constexpr char TEST_SELFSIGNED_CERT_NOT_AFTER[] = "Aug 21 12:26:25 2028 GMT";
