#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_CERT_256_HASH[] =
    "7c5e6153682ada5152e82daa55ed509285fad6c9eada6cf9ce607c269e7c498c";
constexpr char TEST_SELFSIGNED_CERT_1_HASH[] = "2f69de323cee9386cf8341c6fceaa0050ed94500";
constexpr char TEST_SELFSIGNED_CERT_SPKI[] = "HCkWNcliS/8c8jWVG+IkQnM0eYy6VxXdaLzsZWnxoXs=";
constexpr char TEST_SELFSIGNED_CERT_SERIAL[] = "78df1ae91ba732ab28a961dab8b6f2a1389a2ee8";
constexpr char TEST_SELFSIGNED_CERT_NOT_BEFORE[] = "Oct 23 20:45:45 2024 GMT";
constexpr char TEST_SELFSIGNED_CERT_NOT_AFTER[] = "Oct 23 20:45:45 2026 GMT";
