#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_ECDSA_P521_CERT_256_HASH[] =
    "75177da3b513709e9f61e0c300e5669f129a8b285edebd37fbd8e53a286a9649";
constexpr char TEST_SELFSIGNED_ECDSA_P521_CERT_1_HASH[] =
    "545a5abbd732cfa35b0c054d24fc3e173be20642";
constexpr char TEST_SELFSIGNED_ECDSA_P521_CERT_SPKI[] =
    "3OXADmES8Hk4psj6e4uV0IsUApeoebPt7zjznnvAF8o=";
constexpr char TEST_SELFSIGNED_ECDSA_P521_CERT_SERIAL[] =
    "20035206cf418de11f9b9b5be0f69809d0423b69";
constexpr char TEST_SELFSIGNED_ECDSA_P521_CERT_NOT_BEFORE[] = "Aug 22 04:53:04 2026 GMT";
constexpr char TEST_SELFSIGNED_ECDSA_P521_CERT_NOT_AFTER[] = "Aug 21 04:53:04 2028 GMT";
