#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_RSA_1024_CERT_256_HASH[] =
    "14cd8d07c5b02e2904516f08b5d59038ed2c7062df4d67ecb15e4064ef5e2186";
constexpr char TEST_SELFSIGNED_RSA_1024_CERT_1_HASH[] = "fcce4966fd96cd5abfa14abdf577b82258fb9853";
constexpr char TEST_SELFSIGNED_RSA_1024_CERT_SPKI[] =
    "WEvvU64AQLXvmhF9j5PKwdz3dJi1B8KVld2nug41GFI=";
constexpr char TEST_SELFSIGNED_RSA_1024_CERT_SERIAL[] = "1b082e7d858d52b1d05ecc7b89fad5d832d35b44";
constexpr char TEST_SELFSIGNED_RSA_1024_CERT_NOT_BEFORE[] = "Aug 21 19:14:08 2024 GMT";
constexpr char TEST_SELFSIGNED_RSA_1024_CERT_NOT_AFTER[] = "Aug 21 19:14:08 2026 GMT";
