#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_256_HASH[] =
    "09bdcecebec594f3a594cffd4e163ded10a73331895c86d561559d70589eb34e";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_1_HASH[] = "30be905f335a4cb514e159e454cb8267e4c8adfa";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_SPKI[] =
    "zabZtt3m3jVTPmOSzzoY5CiB/4McBxyVn5T9JfnWDQY=";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_SERIAL[] = "6c06f05a408c43930d2886cd8ef5327b33874562";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_NOT_BEFORE[] = "Aug 21 19:14:09 2024 GMT";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_NOT_AFTER[] = "Aug 21 19:14:09 2026 GMT";
