// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_256_HASH[] =
    "70bc94ab5856a89e0b5988bc9b8ae6b1abfa63cc3b4ca2b778dad1d5ec8b409d";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_1_HASH[] = "92cf7873474bf4ec9d506c2759f3fd9f25049897";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_SPKI[] = "RieX1zqkwy068xko7VqJcnoOYHqyT3PaqdKOh3hf2YQ=";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_SERIAL[] = "4fec9a449ab7c8e0ac9561d31e685ba36427ed0d";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_NOT_BEFORE[] = "Oct 16 19:38:41 2024 GMT";
constexpr char TEST_SELFSIGNED_RSA_4096_CERT_NOT_AFTER[] = "Oct 16 19:38:41 2026 GMT";
