#pragma once

// NOLINT(namespace-envoy)
// This file is auto-generated by certs.sh.
constexpr char TEST_SPIFFE_SAN_CERT_256_HASH[] =
    "892e4e59eff748f29f8c6ff4e273ecad02f6fbe1162b7164316dc293d3aa1c5e";
constexpr char TEST_SPIFFE_SAN_CERT_1_HASH[] = "a61ac734b78fc684fdd883974a21c3cfd6c49035";
constexpr char TEST_SPIFFE_SAN_CERT_SPKI[] = "QudfTxtHAjZnbUxp15Thp9OQHO0U4o7ZtXK31CLud90=";
constexpr char TEST_SPIFFE_SAN_CERT_SERIAL[] = "76a469d06159a6ac33d0f0b179d3390bbfe8c35d";
constexpr char TEST_SPIFFE_SAN_CERT_NOT_BEFORE[] = "Aug 22 12:26:26 2026 GMT";
constexpr char TEST_SPIFFE_SAN_CERT_NOT_AFTER[] = "Aug 21 12:26:26 2028 GMT";
