load("//test/extensions/dynamic_modules/test_data/c:test_data.bzl", "test_program")

licenses(["notice"])  # Apache 2

package(default_visibility = ["//test/extensions/dynamic_modules:__pkg__"])

test_program(name = "no_op")
