load("@io_bazel_rules_go//go:def.bzl", "go_library")

licenses(["notice"])  # Apache 2

go_library(
    name = "utils",
    srcs = ["string.go"],
    importpath = "github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/utils",
    visibility = ["//visibility:public"],
)
