load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])  # Apache 2

java_library(
    name = "r8_annotations",
    srcs = ["com/android/tools/r8/annotations/LambdaMethod.java"],
    neverlink = True,
    visibility = ["//:__pkg__"],
)
