load("//test/extensions/dynamic_modules/test_data/go:test_data.bzl", "test_program")

licenses(["notice"])  # Apache 2

test_program(name = "http")

test_program(name = "http_integration_test")

test_program(name = "network_integration_test")

test_program(name = "bootstrap_admin_handler_test")

test_program(name = "bootstrap_cluster_lifecycle_test")

test_program(name = "bootstrap_file_watcher_test")

test_program(name = "bootstrap_function_registry_test")

test_program(name = "bootstrap_init_target_test")

test_program(name = "bootstrap_integration_test")

test_program(name = "bootstrap_listener_lifecycle_test")

test_program(name = "bootstrap_shared_data_test")

test_program(name = "bootstrap_stats_test")

test_program(name = "bootstrap_timer_test")

test_program(name = "cluster_integration_test")

test_program(name = "access_log_integration_test")

test_program(name = "http_stream_callouts_test")

test_program(name = "upstream_http_tcp_bridge")

test_program(name = "bootstrap_http_combined_test")

test_program(name = "udp_integration_test")

test_program(name = "matcher_integration_test")

test_program(name = "listener_integration_test")

test_program(name = "tracer_integration_test")

test_program(name = "load_balancer_integration_test")

test_program(name = "cert_validator_test")
