load("@envoy//bazel:envoy_build_system.bzl", "envoy_cc_test", "envoy_mobile_package")

licenses(["notice"])  # Apache 2

envoy_mobile_package()

envoy_cc_test(
    name = "logger_delegate_test",
    srcs = ["logger_delegate_test.cc"],
    repository = "@envoy",
    deps = [
        "//library/common/api:external_api_lib",
        "//library/common/bridge:utility_lib",
        "//library/common/logger:logger_delegate_lib",
        "//library/common/types:c_types_lib",
    ],
)
