version_info: '1'
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: default
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000
  fcds_config:
    config_source:
      path_config_source:
        path: /usr/local/google/home/kuat/Documents/envoy/configs/fcds/fcds.yaml
        watched_directory:
          path: /usr/local/google/home/kuat/Documents/envoy/configs/fcds
  filter_chain_matcher:
    matcher_tree:
      input:
        name: transport
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.TransportProtocolInput
      exact_match_map:
        map:
          "tls":
            action:
              name: tls
              typed_config:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: default
    on_no_match:
      action:
        name: default
        typed_config:
          "@type": type.googleapis.com/google.protobuf.StringValue
          value: default




