package(default_visibility = ["//visibility:public"])

load("//bazel:envoy_build_system.bzl", "envoy_proto_library")

envoy_proto_library(
    name = "helloworld_proto",
    srcs = [":helloworld.proto"],
)
