FROM python:3.8-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
Add requirements.txt /requirements.txt
RUN pip3 install -q -r /requirements.txt
RUN mkdir /code
ADD ./service.py /code
ENTRYPOINT ["python3", "/code/service.py"]
