#pragma once

// This file is generated by the build system. Do not edit manually.
// The version is the SHA256 hash of the abi.h file.
const char* kAbiVersion = "1ba1ea660354920fa486a9b6fa80917bd6df046ae05c7ebd7a26d4a7155ed7b7";
