FROM envoyproxy/envoy-dev:latest

COPY ./hello/envoy-proxy.yaml /etc/server-envoy-proxy.yaml
RUN chmod go+r /etc/server-envoy-proxy.yaml
CMD ["/usr/local/bin/envoy", "-l", "debug", "-c", "/etc/server-envoy-proxy.yaml"]
