FROM golang:1.19.3-bullseye as builder

WORKDIR /build

COPY hello /build/hello
COPY protos /build/protos

# Build for linux
ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0

WORKDIR /build/hello
RUN go build -o server

# Build the main container (Linux Runtime)
FROM debian:bullseye-slim
WORKDIR /root/

# Copy the linux amd64 binary
COPY --from=builder /build/hello /bin/
