licenses(["notice"])  # Apache 2

exports_files([
    "envoy_api_dependencies.bzl",
    "envoy_dependencies_extra.bzl",
    "envoy_dependencies.bzl",
    "envoy_dependency_imports.bzl",
    "envoy_toolshed_dependencies.bzl",
])
