licenses(["notice"])  # Apache 2

proto_library(
    name = "protos",
    srcs = [
        "oneof.proto",
        "package_move.proto",
        "sample.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_cncf_udpa//udpa/annotations:pkg",
    ],
)
