# We dont build from this dockerfile - we just parse the version, but storing
# here means we get the dependabot updates
FROM moby/buildkit:v0.33.0@sha256:6c2fa84a6b61ccd72899dde4239f8d5717f05f9a8ca6f3cad185fb1a95a94de3
