FROM gcr.io/distroless/base-debian10:nonroot
RUN mkdir -p /etc/envoy

ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml

ARG ENVOY_BINARY_SUFFIX=_stripped
ADD linux/amd64/build_release${ENVOY_BINARY_SUFFIX}/* /usr/local/bin/

EXPOSE 10000

CMD ["envoy", "-c", "/etc/envoy/envoy.yaml"]
