# We dont build from this dockerfile - we just parse the version, but storing
# here means we get the dependabot updates
FROM moby/buildkit:v0.32.2@sha256:28a898719c18a33f4e8000685287fa36fd0dd9560c6440227d3a732d79bb41d8
