FROM gcr.io/distroless/base-nossl-debian11:nonroot@sha256:50562a71d0dfad3a374ec33ab577fc7aab16dfcf37bf95889af6cc58a108dbc1

ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml

ARG ENVOY_BINARY_SUFFIX=_stripped
ADD linux/amd64/build_envoy_release${ENVOY_BINARY_SUFFIX}/* /usr/local/bin/

EXPOSE 10000

ENTRYPOINT ["envoy"]
CMD ["-c", "/etc/envoy/envoy.yaml"]
