FROM gcr.io/distroless/base-debian11@sha256:d65ac1a65a4d82a48ebd0a22aea2acdd95d7abeeda245dfee932ec0018c781f4

ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml

ARG ENVOY_BINARY_SUFFIX=_stripped
ADD linux/amd64/build_envoy_release${ENVOY_BINARY_SUFFIX}/* /usr/local/bin/

EXPOSE 10000

ENTRYPOINT ["envoy"]
CMD ["-c", "/etc/envoy/envoy.yaml"]
