bind(
    name = "ares",
    actual = "//ci/prebuilt:ares",
)

bind(
    name = "event",
    actual = "//ci/prebuilt:event",
)

bind(
    name = "event_pthreads",
    actual = "//ci/prebuilt:event_pthreads",
)

bind(
    name = "googletest",
    actual = "//ci/prebuilt:googletest",
)

bind(
    name = "spdlog",
    actual = "//ci/prebuilt:spdlog",
)

bind(
    name = "ssl",
    actual = "//ci/prebuilt:ssl",
)

bind(
    name = "tclap",
    actual = "//ci/prebuilt:tclap",
)
