FROM debian:buster-slim

RUN apt-get update \
    && apt-get install --no-install-recommends -y python3 python3-pip \
    && apt-get autoremove -y && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install -q flask
RUN mkdir -p /code/data
RUN dd if=/dev/zero of="/code/data/file.txt" bs=1024 count=102400 && \
    dd if=/dev/zero of="/code/data/file.json" bs=1024 count=102400
ADD ./service.py /code
ENTRYPOINT ["python3", "/code/service.py"]
