#// Copyright 2020 Google LLC
// Copyright Envoy Project Authors
// SPDX-License-Identifier: Apache-2.0

#include "source/common/jwt/verify.h"

#include "test/common/jwt/test_common.h"

#include "gtest/gtest.h"

namespace Envoy {
namespace JwtVerify {
namespace {

// Token generated with the following header and payload and kOkPrivateKey.
// Header (kid is not specified):
// {
//   "alg": "RS256",
//   "typ": "JWT"
// }
// Payload:
// {
//   "iss": "628645741881-"
//     "noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com",
//   "sub": "628645741881-"
//     "noabiu23f5a8m8ovd8ucv698lj78vv0l@developer.gserviceaccount.com",
//   "aud": "http://myservice.com/myapi"
// }
const std::string kTokenNoKid =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2Mjg2NDU3NDE4ODEtbm9hYml1M"
    "jNmNWE4bThvdmQ4dWN2Njk4bGo3OHZ2MGxAZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20"
    "iLCJzdWIiOiI2Mjg2NDU3NDE4ODEtbm9hYml1MjNmNWE4bThvdmQ4dWN2Njk4bGo3OHZ2MGxAZ"
    "GV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJodHRwOi8vbXlzZXJ2aWNlLmN"
    "vbS9teWFwaSJ9.gq_4ucjddQDjYK5FJr_kXmMo2fgSEB6Js1zopcQLVpCKFDNb-TQ97go0wuk5"
    "_vlSp_8I2ImrcdwYbAKqYCzcdyBXkAYoHCGgmY-v6MwZFUvrIaDzR_M3rmY8sQ8cdN3MN6ZRbB"
    "6opHwDP1lUEx4bZn_ZBjJMPgqbIqGmhoT1UpfPF6P1eI7sXYru-4KVna0STOynLl3d7JYb7E-8"
    "ifcjUJLhat8JR4zR8i4-zWjn6d6j_NI7ZvMROnao77D9YyhXv56zfsXRatKzzYtxPlQMz4AjP-"
    "bUHfbHmhiIOOAeEKFuIVUAwM17j54M6VQ5jnAabY5O-ermLfwPiXvNt2L2SA==";

TEST(VerifyX509Test, NoKidToken) {
  Jwt jwt;
  EXPECT_EQ(jwt.parseFromString(kTokenNoKid), Status::Ok);

  auto jwks = Jwks::createFrom(kPublicKeyX509, Jwks::Type::JWKS);
  EXPECT_EQ(jwks->getStatus(), Status::Ok);

  EXPECT_EQ(verifyJwt(jwt, *jwks), Status::Ok);

  fuzzJwtSignature(jwt, [&jwks](const Jwt& jwt) {
    EXPECT_EQ(verifyJwt(jwt, *jwks), Status::JwtVerificationFail);
  });
}

// A token generated by using
// https://github.com/cloudendpoints/endpoints-tools/blob/master/auth/generate-jwt.py
// ./generate-jwt.py --iss="fake.issuer" "fake.audience" sa_file
const std::string kRealToken =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjgyY2ZkNzk3OTAzMDYzYTBiNzhjZT"
    "FjYmY1ZTJmZTAzNmE2ZGUyNDIifQ."
    "eyJpc3MiOiJmYWtlLmlzc3VlciIsImlhdCI6MTU3ODQ0ODEwNiwiYXVkIjoiZmFrZS5hdWRpZW"
    "5jZSIsImV4cCI6MTU3ODQ1MTcwNiwic3ViIjoiZmFrZS5pc3N1ZXIifQ."
    "YeKxQvJurL2XHbLdV5pAYW1daumTyLS1ShtEqYJJvMV3kkAG0HRspxrUwkRqRsnchaWjkxzcj-"
    "cKg-38LM_hfRIAJ9kyjoiESmD8Oq2cMK_go8Ejq_"
    "6YS9CqEnqzR99RRL1iZRVgzj8Wgv7vL3sbbaOBANNmVLr9E5Y2_3_-"
    "SMYev586yQOkXkV3J7HaW5avCWl0bJAbR_-gB2Ku2-Em-12-Wh20_NuKIBje0OkkJm0YFHdtm_"
    "EBFoc54yQX9yrlyHCEYv7nLvoXZD268j7Xw5_FFhAuxeSS5FKFOxiBEEowSLFw3IgRqFaMfl_"
    "qvQQWNDBQBziIhbyLujpy4ZnmYw";

TEST(VerifyX509Test, RealToken) {
  Jwt jwt;
  EXPECT_EQ(jwt.parseFromString(kRealToken), Status::Ok);

  auto jwks = Jwks::createFrom(kRealX509Jwks, Jwks::Type::JWKS);
  EXPECT_EQ(jwks->getStatus(), Status::Ok);

  EXPECT_EQ(verifyJwt(jwt, *jwks, 1), Status::Ok);

  fuzzJwtSignature(jwt, [&jwks](const Jwt& jwt) {
    EXPECT_EQ(verifyJwt(jwt, *jwks, 1), Status::JwtVerificationFail);
  });
}

} // namespace
} // namespace JwtVerify
} // namespace Envoy
