syntax = "proto3";

package envoy.config.trace.v3;

import "google/protobuf/wrappers.proto";
import "third_party/envoy/src/api/envoy/config/core/v3/extension.proto";
import "third_party/envoy/src/api/envoy/config/core/v3/grpc_service.proto";
import "third_party/envoy/src/api/envoy/config/core/v3/http_service.proto";
import "third_party/protoc_gen_validate/validate/validate.proto";
import "third_party/udpa/udpa/annotations/migrate.proto";
import "third_party/udpa/udpa/annotations/status.proto";

option java_package = "io.envoyproxy.envoy.config.trace.v3";
option java_outer_classname = "OpentelemetryProto";
option java_multiple_files = true;
option go_package = "github.com/envoyproxy/go-control-plane/envoy/config/trace/v3;tracev3";
option (udpa.annotations.file_status).package_version_status = ACTIVE;

// [#protodoc-title: OpenTelemetry tracer]

// Configuration for the OpenTelemetry tracer.
//  [#extension: envoy.tracers.opentelemetry]
// [#next-free-field: 11]
message OpenTelemetryConfig {
  // OTLP exporter specification. Exactly one of ``grpc_service``,
  // ``http_service``, or ``exporter`` must be used.
  oneof otlp_exporter {
    option (validate.required) = true;

    // The upstream gRPC cluster that will receive OTLP traces.
    // Note that the tracer drops traces if the server does not read data fast
    // enough. Only one of ``grpc_service``, ``http_service``, ``exporter`` may
    // be used.
    core.v3.GrpcService grpc_service = 1;

    // The upstream HTTP cluster that will receive OTLP traces.
    // Only one of ``grpc_service``, ``http_service``, ``exporter`` may be used.
    //
    // .. note::
    //
    //   The ``request_headers_to_add`` property in the OTLP HTTP exporter
    //   service supports substitution formatters. The formatters cannot access
    //   any HTTP or connection properties, but can load content such as
    //   environment variables or files or secrets.
    core.v3.HttpService http_service = 3;

    // Specifies the custom exporter to be used by the OpenTelemetry tracer.
    // Only one of ``grpc_service``, ``http_service``, ``exporter`` may be used.
    // [#extension-category: envoy.tracers.opentelemetry.exporters]
    core.v3.TypedExtensionConfig exporter = 10;
  }

  // The name for the service. This will be populated in the ResourceSpan
  // Resource attributes. If it is not provided, it will default to
  // "unknown_service:envoy".
  string service_name = 2;

  // An ordered list of resource detectors
  // [#extension-category: envoy.tracers.opentelemetry.resource_detectors]
  repeated core.v3.TypedExtensionConfig resource_detectors = 4;

  // Specifies the sampler to be used by the OpenTelemetry tracer.
  // The configured sampler implements the Sampler interface defined by the OpenTelemetry specification.
  // This field can be left empty. In this case, the default Envoy sampling decision is used.
  //
  // See: `OpenTelemetry sampler specification <https://opentelemetry.io/docs/specs/otel/trace/sdk/#sampler>`_
  // [#extension-category: envoy.tracers.opentelemetry.samplers]
  core.v3.TypedExtensionConfig sampler = 5;

  // Envoy caches the span in memory when the OpenTelemetry backend service is temporarily unavailable.
  // This field specifies the maximum number of spans that can be cached. If not specified, the
  // default is 1024.
  google.protobuf.UInt32Value max_cache_size = 6;

  // Specifies whether to set the telemetry SDK resource attributes.
  // The following attributes will be set:
  //
  // - telemetry.sdk.language
  // - telemetry.sdk.name
  // - telemetry.sdk.version
  //
  // If not specified, the default is to set these attributes.
  google.protobuf.BoolValue set_telemetry_sdk_resource_attributes = 7;

  // Specifies whether to set the ``service.name`` resource attribute.
  // If not specified, the default is to set this attribute.
  google.protobuf.BoolValue set_service_name_resource_attribute = 8;

  // Specifies whether to set the instrumentation scope name ("envoy") and version on emitted traces.
  // If not specified, the default is to set the instrumentation scope name and version.
  google.protobuf.BoolValue set_instrumentation_scope = 9;
}
