import datetime
import sys
from cryptography import x509
from cryptography.x509.oid import NameOID, ExtendedKeyUsageOID
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa


def generate_certs():
    # Load existing CA cert and key from the current directory
    try:
        with open("upstreamcacert.pem", "rb") as f:
            ca_cert = x509.load_pem_x509_certificate(f.read())
        with open("upstreamcakey.pem", "rb") as f:
            ca_key = serialization.load_pem_private_key(f.read(), password=None)
        print("Successfully loaded existing upstream CA cert and key.")
    except Exception as e:
        print(
            f"Failed to load existing CA (make sure to run this script in the certs directory): {e}"
        )
        sys.exit(1)

    # Load existing server private key to extract its public key
    try:
        with open("upstreamkey.pem", "rb") as f:
            server_private_key = serialization.load_pem_private_key(f.read(), password=None)
        server_public_key = server_private_key.public_key()
        print("Successfully loaded existing upstream private key and extracted public key.")
    except Exception as e:
        print(f"Failed to load existing upstream private key: {e}")
        sys.exit(1)

    # Generate Server cert with NUL in SAN and proper extensions
    server_subject = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, "Test Server"),
    ])

    san = x509.SubjectAlternativeName([x509.DNSName("example.com\x00.attacker.com")])

    try:
        server_cert = x509.CertificateBuilder().subject_name(server_subject).issuer_name(
            ca_cert.subject  # Sign with existing CA subject
        ).public_key(server_public_key  # Reuse existing server public key!
                    ).serial_number(x509.random_serial_number()).not_valid_before(
                        datetime.datetime.utcnow() - datetime.timedelta(days=1)).not_valid_after(
                            datetime.datetime.utcnow()
                            + datetime.timedelta(days=730)  # 730 days (2 years) to match certs.sh
                        ).add_extension(
                            x509.BasicConstraints(ca=False, path_length=None),
                            critical=True).add_extension(
                                x509.KeyUsage(
                                    digital_signature=True,
                                    content_commitment=False,
                                    key_encipherment=True,
                                    data_encipherment=False,
                                    key_agreement=False,
                                    key_cert_sign=False,
                                    crl_sign=False,
                                    encipher_only=False,
                                    decipher_only=False),
                                critical=True).add_extension(
                                    x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]),
                                    critical=True).add_extension(
                                        san, critical=False).sign(
                                            ca_key, hashes.SHA256())  # Sign with existing CA key

        print(
            "Successfully generated robust cert with NUL signed by existing CA and reusing server key!"
        )

    except Exception as e:
        print(f"Direct generation failed: {e}")
        sys.exit(1)

    # Write Server cert with human-readable comments prepended
    comment = """ Generated by generate_nul_cert.py (DO NOT EDIT)!!
# Human-readable Certificate Info:
# Subject: CN=Test Server
# Issuer: CN=Test CA
# Subject Alternative Name (SAN):
#   DNS: example.com[NUL].attacker.com
#
# Note the embedded NUL byte (\\x00) between 'example.com' and '.attacker.com'.
# Vulnerable validators (like Envoy's deprecated verifySubjectAltName path before the fix)
# will truncate the SAN at the NUL byte and match it against 'example.com'.
#
# Raw SAN Hex:
#   65 78 61 6d 70 6c 65 2e 63 6f 6d 00 2e 61 74 74 61 63 6b 65 72 2e 63 6f 6d
#   e  x  a  m  p  l  e  .  c  o  m  \\0 .  a  t  t  a  c  k  e  r  .  c  o  m
#                                    ^^ NUL byte
#
"""
    with open("san_nul_servercert.pem", "wb") as f:
        f.write(comment.encode("utf-8"))
        f.write(server_cert.public_bytes(serialization.Encoding.PEM))


if __name__ == "__main__":
    generate_certs()
