FROM golang
COPY ./server /go/src/github.com/envoyproxy/envoy/example/load_reporting_service/server
COPY *.go /go/src/github.com/envoyproxy/envoy/example/load_reporting_service/
COPY go.sum /go/src/github.com/envoyproxy/envoy/example/load_reporting_service
COPY go.mod /go/src/github.com/envoyproxy/envoy/example/load_reporting_service

WORKDIR /go/src/github.com/envoyproxy/envoy/example/load_reporting_service
RUN go mod download
RUN go install /go/src/github.com/envoyproxy/envoy/example/load_reporting_service

CMD ["go","run","main.go"]
