FROM envoyproxy/envoy-alpine-dev:latest

RUN apk update && apk add py3-pip bash curl
RUN mkdir /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
COPY . ./code

RUN pip3 install -q Flask==0.11.1

RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
