name: Publish (containers)

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      dockerhub-write-token:
      ghcr-write-token:
    inputs:
      dev:
        required: true
        type: boolean
        default: true
      dockerhub-repo:
        required: true
        default: envoy
        type: string
      dockerhub-username:
        required: true
        type: string
      ghcr-repo:
        required: false
        default: envoy
        type: string
      ghcr-username:
        required: true
        type: string
      sha:
        required: true
        type: string
      target-branch:
        required: true
        type: string
      trusted:
        required: true
        type: boolean
      version-major:
        required: false
        type: number
      version-minor:
        required: false
        type: number
      version-patch:
        required: false
        type: number

concurrency:
  group: >-
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.event.workflow.id }}-publish-release-container
  cancel-in-progress: true


jobs:
  push-manifests:
    name: Create manifests (${{ inputs.trustred && 'dry run' || 'push' }})
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
    - name: Generate manifest configuration (dev)
      id: dev-config
      if: ${{ inputs.dev && inputs.target-branch == 'main' }}
      uses: envoyproxy/toolshed/actions/jq@1f5b552c6749502b885cb8cf23549b929e745547  # actions-v0.4.17
      with:
        input-format: yaml
        filter: >-
          {manifests:
            [.[] as $e
             | ({name: "${{ inputs.dockerhub-repo }}", registry: "docker.io/envoyproxy"} + $e)
               ${{ (inputs.trusted && (inputs.target-branch == 'main' || ! inputs.dev))
                   && format(', ({{name: "{0}", registry: "ghcr.io/envoyproxy"}} + $e)', inputs.ghcr-repo)
                   || '' }}]}
        input: |
          - tag: dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy.{arch}.tar
            additional-tags:
            - dev-${{ github.sha }}
          - tag: contrib-dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-contrib.{arch}.tar
            additional-tags:
            - contrib-dev-${{ github.sha }}
          - tag: contrib-debug-dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-contrib-debug.{arch}.tar
            additional-tags:
            - contrib-debug-dev-${{ github.sha }}
          - tag: contrib-distroless-dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-contrib-distroless.{arch}.tar
            additional-tags:
            - contrib-distroless-dev-${{ github.sha }}
          - tag: debug-dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-debug.{arch}.tar
            additional-tags:
            - debug-dev-${{ github.sha }}
          - tag: distroless-dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-distroless.{arch}.tar
            additional-tags:
            - distroless-dev-${{ github.sha }}
          - tag: google-vrp-dev
            architectures:
            - amd64
            artifact-pattern: envoy-google-vrp.{arch}.tar
            additional-tags:
            - google-vrp-dev-${{ github.sha }}
          - tag: tools-dev
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-tools.{arch}.tar
            additional-tags:
            - tools-dev-${{ github.sha }}

    - name: Generate manifest configuration (release)
      uses: envoyproxy/toolshed/actions/jq@1f5b552c6749502b885cb8cf23549b929e745547  # actions-v0.4.17
      id: release-config
      if: ${{ ! inputs.dev || ! inputs.target-branch != 'main' }}
      with:
        input-format: yaml
        filter: >-
          .version as $v
          | {manifests:
              [.manifests[]
               | select(
                   (.tag | test("contrib-distroless") | not)
                   or ($v.major > 1 or ($v.major == 1 and $v.minor >= 37)))
               | . as $e
               | ({name: "${{ inputs.dockerhub-repo }}", registry: "docker.io/envoyproxy"} + $e)
                 ${{ (inputs.trusted && (inputs.target-branch == 'main' || ! inputs.dev))
                     && format(', ({{name: "{0}", registry: "ghcr.io/envoyproxy"}} + $e)', inputs.ghcr-repo)
                     || '' }}]}
        input: |
          version:
            major: ${{ inputs.version-major }}
            minor: ${{ inputs.version-minor }}
          manifests:
          - tag: v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy.{arch}.tar
            additional-tags:
            - v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: contrib-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-contrib.{arch}.tar
            additional-tags:
            - contrib-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: contrib-debug-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-contrib-debug.{arch}.tar
            additional-tags:
            - contrib-debug-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: contrib-distroless-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-contrib-distroless.{arch}.tar
            additional-tags:
            - contrib-distroless-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: debug-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-debug.{arch}.tar
            additional-tags:
            - debug-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: distroless-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-distroless.{arch}.tar
            additional-tags:
            - distroless-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: google-vrp-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            artifact-pattern: envoy-google-vrp.{arch}.tar
            additional-tags:
            - google-vrp-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest
          - tag: tools-v${{ inputs.version-major }}.${{ inputs.version-minor }}.${{ inputs.version-patch }}
            architectures:
            - amd64
            - arm64
            artifact-pattern: envoy-tools.{arch}.tar
            additional-tags:
            - tools-v${{ inputs.version-major }}.${{ inputs.version-minor }}-latest

    - name: Authenticate GHCR
      if: ${{ inputs.trusted && (inputs.target-branch == 'main' || ! inputs.dev) }}
      shell: bash
      env:
        GHCR_USERNAME: ${{ inputs.ghcr-username }}
        GHCR_PASSWORD: ${{ secrets.ghcr-write-token }}
      run: |
        echo "::group::Authenticating with GHCR"
        echo "$GHCR_PASSWORD" | buildah login --username "$GHCR_USERNAME" --password-stdin ghcr.io
        echo "::endgroup::"

    - name: Collect and push OCI artifacts
      uses: envoyproxy/toolshed/actions/oci/collector@1f5b552c6749502b885cb8cf23549b929e745547  # actions-v0.4.17
      with:
        artifacts-pattern: oci.*
        manifest-config: ${{ steps.dev-config.outputs.value || steps.release-config.outputs.value }}
        dry-run: ${{ ! inputs.trusted || (inputs.target-branch != 'main' && inputs.dev) }}
        dockerhub-username: ${{ inputs.trusted && inputs.dockerhub-username || '' }}
        dockerhub-password: ${{ inputs.trusted && secrets.dockerhub-write-token || '' }}
