name: Upload to GCS

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      gcp-key:
        required: true
    inputs:
      artifacts:
        description: JSON array of artifacts to upload to GCS
        type: string
        required: true


jobs:
  upload:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        artifact: ${{ fromJSON(inputs.artifacts) }}
    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.artifact }}
    - uses: envoyproxy/toolshed/actions/jq@3a721916b4cf6338784230c7b940a249d6a64341  # actions-v0.4.21
      id: metadata
      with:
        input: ${{ matrix.artifact }}/gcs-metadata.json
        input-format: json-path
    - run: |
        rm -rf ${{ matrix.artifact }}/gcs-metadata.json
    - uses: envoyproxy/toolshed/actions/gcp/setup@3a721916b4cf6338784230c7b940a249d6a64341  # actions-v0.4.21
      with:
        key: ${{ secrets.gcp-key }}
    - uses: envoyproxy/toolshed/actions/gcs/artefact/sync@3a721916b4cf6338784230c7b940a249d6a64341  # actions-v0.4.21
      with:
        bucket: ${{ fromJSON(steps.metadata.outputs.value).bucket }}
        path: ${{ matrix.artifact }}
        path-upload: ${{ matrix.artifact }}
        sha: ${{ fromJSON(steps.metadata.outputs.value).sha }}
        redirect: ${{ fromJSON(steps.metadata.outputs.value).redirect }}
