name: Envoy/lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
      with:
        python-version: "3.11"
    - run: pip install envoy.code.check>=0.5.13
    - run: |
        envoy.code.check . -c glint shellcheck yamllint python_flake8
