name: Toolchain default behavior test

permissions:
  contents: read
on:
  pull_request:
    paths:
    - .bazelrc
    - .github/workflows/toolchain-test.yml
    - ci/matrix/**
    - tools/toolchain
concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  toolchain-test:
    runs-on: ubuntu-22.04
    if: github.repository == 'envoyproxy/envoy'
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: "GCC only"
          service: "gcc"
        - name: "LLVM only"
          service: "llvm"
        - name: "Both GCC & LLVM"
          service: "all"
        - name: "No compilers"
          service: "none"
    name: "Test: ${{ matrix.name }}"
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Run matrix test
      run: |
        cd ci/matrix
        export UID
        docker compose run --rm --build ${{ matrix.service }}
