licenses(["notice"])  # Apache 2

platform(
    name = "macos",
    constraint_values = [
        "@platforms//cpu:arm64",
        "@platforms//os:macos",
    ],
    exec_properties = {
        "Pool": "macos14",
    },
)
